project:
  type: website
  output-dir: docs


website:
  title: "Pathways taken after high school - Northeast"
  navbar:
    left:
      - href: index.qmd
        text: Summary
      - text: Data Prep and Summaries
        icon: fa-gear
        menu:
          - text: K12Enrollment
            href: k12enrollment.qmd
          - text: K12Orgs
            href: k12orgs.qmd
          - text: ACT
            href: act.qmd
          - text: AP
            href: ap.qmd
          - text: CTEEnrollment
            href: cteenrollment.qmd
          - text: CTEDemographics
            href: ctedemographics.qmd
          - text: Assessments
            href: assessments.qmd
          - text: SAT
            href: sat.qmd
          - text: National Student Clearinghouse - Enrollment
            href: nscenrollment.qmd
          - text: Employment
            href: employment.qmd


format:
  html:
    theme: cosmo
    toc: true