{
  "hash": "8656a5f969955c238a2e55404a91ac64",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multivariate Confirmation Analysis - Non-college grads\"\neditor: visual\n---\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmaster.original <- read_csv(\"Data/SLEDS/Masters/After analysis/Master-final-after-mca.csv\")\n\nmaster.states <- read_csv(\"Data/SLEDS/Masters/States/annual-seven-states.csv\") %>%\n  filter(grad.year %in% c(\"grad.year.1\", \"grad.year.5\", \"grad.year.10\")) %>%\n  select(PersonID, grad.year, states) %>%\n  pivot_wider(names_from = grad.year, values_from = states)\n\nmaster <- master.original %>%\n  left_join(master.states, by = \"PersonID\")\n\nkable(head(master))\n```\n\n::: {.cell-output-display}\n\n\n| PersonID| K12OrganizationID|OrganizationName                   |county.name | countyfp|Dem_Desc             |edr                  | grad.year|grad.year.covid |Gender | economic.status| pseo.participant| SpecialEdStatus| non.english.home|RaceEthnicity | n.years.attended| ACTCompositeScore|took.ACT | ap.exam| total.cte.courses.taken| ACTE.SPED| Agriculture..Food..and.Natural.Resources| Architecture...Construction| Arts..A.V.Technology...Communication| Business..Management...Administrative| Diversified| Education...Training| Finance| Government...Public.Administration| Health.Science| Hospitality...Tourism| Human.Services| Information.Technology| Law..Public.Safety...Security| Manufacturing| Marketing| Program.Area..Diversified.| Science..Technology..Engineering....Mathematics| STEM| Transportation..Distribution...Logistics| Work.Experience.Handicapped| Work.Experience.Handicapped..16.20..on.IEP.| Work.Experience.Career.Exploration..age.14.15.on.I| Work.Experience.Disadvantaged| Youth.Apprenticeship|cte.achievement               | english.learner| MCA.M| MCA.R| MCA.S|attended.ps | first.attend.ps| attended.ps.first.year| attended.ps.years.hsgrad| n.institutions| first.InstitutionSector| ps.sector.1| ps.sector.2| ps.sector.3| ps.sector.4| ps.sector.5| ps.sector.6| ps.sector.7| ps.sector.8| ps.sector.9|ps.in.same.ruca              |ps.in.same.edr              |ps.in.same.pr              |ps.in.MN              | hs.grad.year|ps.attended.in.same.ruca     |ps.attended.in.same.edr     |ps.attended.in.same.pr     |ps.attended.in.MN     |ps.grad      | min.ps.grad.year| max.ps.grad.year| years.between.grads|ps.grad.InstitutionSector |highest.cred.level         |ps.grad.in.same.ruca |ps.grad.in.same.edr |ps.grad.in.same.pr |ps.grad.in.MN |ps.grad.location    |mn.emp.record.hs.grad.year |mn.emp.record.hs.grad.year.2 |mn.emp.record.hs.grad.year.7 |meaningful.emp.hs.grad.year |meaningful.emp.hs.grad.year.2 |meaningful.emp.hs.grad.year.7 |hs.grad.year.county.match |hs.grad.year.2.county.match |hs.grad.year.7.county.match |hs.grad.year.edr.match |hs.grad.year.2.edr.match |hs.grad.year.7.edr.match |hs.grad.year.region.match |hs.grad.year.2.region.match |hs.grad.year.7.region.match |hs.grad.year.state.match |hs.grad.year.2.state.match |hs.grad.year.7.state.match |ind.match.hs.grad.year |ind.match.hs.grad.year.2 |ind.match.hs.grad.year.7 | avg.unemp.rate| wages.3year.avg| avg.wages.pct.state|grad.year.10          |grad.year.1           |grad.year.5                        |\n|--------:|-----------------:|:----------------------------------|:-----------|--------:|:--------------------|:--------------------|---------:|:---------------|:------|---------------:|----------------:|---------------:|----------------:|:-------------|----------------:|-----------------:|:--------|-------:|-----------------------:|---------:|----------------------------------------:|---------------------------:|------------------------------------:|-------------------------------------:|-----------:|--------------------:|-------:|----------------------------------:|--------------:|---------------------:|--------------:|----------------------:|-----------------------------:|-------------:|---------:|--------------------------:|-----------------------------------------------:|----:|----------------------------------------:|---------------------------:|-------------------------------------------:|--------------------------------------------------:|-----------------------------:|--------------------:|:-----------------------------|---------------:|-----:|-----:|-----:|:-----------|---------------:|----------------------:|------------------------:|--------------:|-----------------------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|:----------------------------|:---------------------------|:--------------------------|:---------------------|------------:|:----------------------------|:---------------------------|:--------------------------|:---------------------|:------------|----------------:|----------------:|-------------------:|:-------------------------|:--------------------------|:--------------------|:-------------------|:------------------|:-------------|:-------------------|:--------------------------|:----------------------------|:----------------------------|:---------------------------|:-----------------------------|:-----------------------------|:-------------------------|:---------------------------|:---------------------------|:----------------------|:------------------------|:------------------------|:-------------------------|:---------------------------|:---------------------------|:------------------------|:--------------------------|:--------------------------|:----------------------|:------------------------|:------------------------|--------------:|---------------:|-------------------:|:---------------------|:---------------------|:----------------------------------|\n|  1621067|            140965|PERHAM SENIOR HIGH                 |Otter Tail  |      111|Town/rural mix       |EDR 4 - West Central |      2014|Pre-covid grad  |M      |               0|                1|               0|                0|White         |                3|                27|Yes      |       1|                       6|         0|                                        1|                           1|                                    0|                                     1|           0|                    0|       0|                                  0|              0|                     0|              0|                      0|                             0|             0|         0|                          0|                                               0|    0|                                        3|                           0|                                           0|                                                  0|                             0|                    0|CTE Participant               |               0|     4|     4|     4|Yes         |        20140902|                   2014|                        0|              3|                       1|           1|           0|           0|           0|           0|           0|           0|           0|           0|Inside and outside same RUCA |Outside EDR                 |Outside PR                 |Inside and outside MN |         2014|Inside and outside same RUCA |Outside EDR                 |Outside PR                 |Inside and outside MN |Y            |             2017|             2017|                   3|1                         |Bachelor degree or higher  |Outside RUCA         |Outside EDR         |Outside PR         |Outside MN    |PS grad outside MN  |MN emp record              |MN emp record                |No MN emp record             |No meaningful emp           |No meaningful emp             |No MN emp record              |No meaningful emp         |No meaningful emp           |No MN emp record            |No meaningful emp      |No meaningful emp        |No MN emp record         |No meaningful emp         |No meaningful emp           |No MN emp record            |No meaningful emp        |No meaningful emp          |No MN emp record           |No meaningful emp      |No meaningful emp        |No MN emp record         |       5.166667|        40785.67|           0.8487053|After 2023            |Attending ps          |No MN emp record, not attending ps |\n|  3645119|            177901|OSAKIS SECONDARY                   |Douglas     |       41|Town/rural mix       |EDR 4 - West Central |      2019|Pre-covid grad  |F      |               0|                1|               0|                0|White         |                3|                21|Yes      |       0|                       3|         0|                                        1|                           0|                                    0|                                     1|           0|                    0|       0|                                  0|              0|                     0|              0|                      0|                             0|             0|         0|                          0|                                               0|    0|                                        1|                           0|                                           0|                                                  0|                             0|                    0|No CTE                        |               0|     4|     3|     3|Yes         |        20190826|                   2019|                        0|              1|                       1|           1|           0|           0|           0|           0|           0|           0|           0|           0|Outside RUCA                 |Outside EDR                 |Outside PR                 |Outside MN            |         2019|Outside RUCA                 |Outside EDR                 |Outside PR                 |Outside MN            |Y            |             2022|             2022|                   3|1                         |Bachelor degree or higher  |Outside RUCA         |Outside EDR         |Outside PR         |Outside MN    |PS grad outside MN  |MN emp record              |MN emp record                |After 2023                   |No meaningful emp           |No meaningful emp             |After 2023                    |No meaningful emp         |No meaningful emp           |After 2023                  |No meaningful emp      |No meaningful emp        |After 2023               |No meaningful emp         |No meaningful emp           |After 2023                  |No meaningful emp        |No meaningful emp          |After 2023                 |No meaningful emp      |No meaningful emp        |After 2023               |       3.133333|        50192.00|           0.8966593|After 2023            |Attending ps          |After 2023                         |\n|  1279027|            216983|BEMIDJI SENIOR HIGH                |Beltrami    |        7|Town/rural mix       |EDR 2 - Headwaters   |      2023|Post-covid grad |F      |               1|                1|               0|                0|Unknown       |                3|                26|Yes      |       1|                       1|         0|                                        0|                           0|                                    0|                                     0|           0|                    0|       0|                                  0|              0|                     0|              1|                      0|                             0|             0|         0|                          0|                                               0|    0|                                        0|                           0|                                           0|                                                  0|                             0|                    0|CTE Participant               |               0|     4|     4|     4|Yes         |        20230821|                   2023|                        0|              1|                       1|           1|           0|           0|           0|           0|           0|           0|           0|           0|Outside RUCA                 |Outside EDR                 |Outside PR                 |Outside MN            |         2023|Outside RUCA                 |Outside EDR                 |Outside PR                 |Outside MN            |Attending ps |               NA|               NA|                  NA|Attending ps              |Attending ps               |NA                   |NA                  |NA                 |NA            |Attending ps        |MN emp record              |After 2023                   |After 2023                   |No meaningful emp           |After 2023                    |After 2023                    |No meaningful emp         |After 2023                  |After 2023                  |No meaningful emp      |After 2023               |After 2023               |No meaningful emp         |After 2023                  |After 2023                  |No meaningful emp        |After 2023                 |After 2023                 |No meaningful emp      |After 2023               |After 2023               |       3.833333|        51912.33|           0.7418874|After 2023            |After 2023            |After 2023                         |\n|  2500266|            150483|EAST GRAND FORKS SENIOR HIGH       |Polk        |      119|Urban/town/rural mix |EDR 1 - Northwest    |      2009|Pre-covid grad  |M      |               0|               NA|               1|                0|White         |                3|                NA|No       |       0|                       3|         0|                                        0|                           0|                                    0|                                     0|           0|                    1|       0|                                  0|              0|                     0|              0|                      0|                             0|             0|         0|                          0|                                               0|    0|                                        2|                           0|                                           0|                                                  0|                             0|                    0|CTE Concentrator or Completor |               0|     1|     1|    NA|No          |              NA|                     NA|                       NA|              0|                      NA|           0|           0|           0|           0|           0|           0|           0|           0|           0|NA                           |NA                          |NA                         |NA                    |         2009|NA                           |NA                          |NA                         |NA                    |No           |               NA|               NA|                  NA|Never attended ps         |Did not graduate ps        |NA                   |NA                  |NA                 |NA            |Did not graduate ps |MN emp record              |MN emp record                |No MN emp record             |Meaningful emp              |Meaningful emp                |No MN emp record              |Location match            |Location match              |No MN emp record            |Location match         |Location match           |No MN emp record         |Location match            |Location match              |No MN emp record            |Location match           |Location match             |No MN emp record           |No ind match           |No ind match             |No MN emp record         |       5.166667|        34774.33|           0.8327785|Meaningful emp County |Meaningful emp County |Meaningful emp MN                  |\n|  5556115|            189828|GREENBUSH-MIDDLE RIVER SENIOR HIGH |Roseau      |      135|Town/rural mix       |EDR 1 - Northwest    |      2020|Post-covid grad |M      |               0|                0|               0|                0|White         |                3|                NA|No       |       0|                       4|         0|                                        0|                           3|                                    0|                                     0|           0|                    0|       0|                                  0|              1|                     0|              0|                      0|                             0|             0|         0|                          0|                                               0|    0|                                        0|                           0|                                           0|                                                  0|                             0|                    0|CTE Concentrator or Completor |               0|     3|     4|     3|Yes         |        20200824|                   2020|                        0|              2|                       4|           0|           0|           0|           1|           0|           0|           0|           0|           0|In same RUCA                 |Inside and outside same EDR |Inside and outside same PR |In MN                 |         2020|In same RUCA                 |Inside and outside same EDR |Inside and outside same PR |In MN                 |Y            |             2021|             2021|                   1|4                         |Less than Associate Degree |In same RUCA         |Outside EDR         |Outside PR         |In MN         |PS grad MN          |No MN emp record           |MN emp record                |After 2023                   |No MN emp record            |Meaningful emp                |After 2023                    |No MN emp record          |No location match           |After 2023                  |No MN emp record       |Location match           |After 2023               |No MN emp record          |Location match              |After 2023                  |No MN emp record         |Location match             |After 2023                 |No MN emp record       |No ind match             |After 2023               |       4.166667|        49644.00|           0.8489443|After 2023            |Meaningful emp EDR    |After 2023                         |\n|  1950620|            200829|DETROIT LAKES SENIOR HIGH          |Becker      |        5|Urban/town/rural mix |EDR 4 - West Central |      2021|Post-covid grad |F      |               0|                0|               0|                0|Unknown       |                3|                16|Yes      |       0|                       7|         0|                                        0|                           0|                                    0|                                     0|           3|                    1|       1|                                  0|              2|                     0|              0|                      0|                             0|             0|         0|                          0|                                               0|    0|                                        0|                           0|                                           0|                                                  0|                             0|                    0|CTE Concentrator or Completor |               0|     3|     3|     3|Yes         |        20210823|                   2021|                        0|              2|                       1|           1|           0|           0|           1|           0|           0|           0|           0|           0|In same RUCA                 |Outside EDR                 |Outside PR                 |Inside and outside MN |         2021|In same RUCA                 |Outside EDR                 |Outside PR                 |Inside and outside MN |Attending ps |               NA|               NA|                  NA|Attending ps              |Attending ps               |NA                   |NA                  |NA                 |NA            |Attending ps        |MN emp record              |MN emp record                |After 2023                   |Meaningful emp              |Meaningful emp                |After 2023                    |Location match            |No location match           |After 2023                  |Location match         |No location match        |After 2023               |Location match            |No location match           |After 2023                  |Location match           |Location match             |After 2023                 |No ind match           |No ind match             |After 2023               |       4.966667|        51833.67|           0.8329325|After 2023            |Attending ps          |After 2023                         |\n\n\n:::\n\n```{.r .cell-code}\nkable(names(master))\n```\n\n::: {.cell-output-display}\n\n\n|x                                                  |\n|:--------------------------------------------------|\n|PersonID                                           |\n|K12OrganizationID                                  |\n|OrganizationName                                   |\n|county.name                                        |\n|countyfp                                           |\n|Dem_Desc                                           |\n|edr                                                |\n|grad.year                                          |\n|grad.year.covid                                    |\n|Gender                                             |\n|economic.status                                    |\n|pseo.participant                                   |\n|SpecialEdStatus                                    |\n|non.english.home                                   |\n|RaceEthnicity                                      |\n|n.years.attended                                   |\n|ACTCompositeScore                                  |\n|took.ACT                                           |\n|ap.exam                                            |\n|total.cte.courses.taken                            |\n|ACTE.SPED                                          |\n|Agriculture..Food..and.Natural.Resources           |\n|Architecture...Construction                        |\n|Arts..A.V.Technology...Communication               |\n|Business..Management...Administrative              |\n|Diversified                                        |\n|Education...Training                               |\n|Finance                                            |\n|Government...Public.Administration                 |\n|Health.Science                                     |\n|Hospitality...Tourism                              |\n|Human.Services                                     |\n|Information.Technology                             |\n|Law..Public.Safety...Security                      |\n|Manufacturing                                      |\n|Marketing                                          |\n|Program.Area..Diversified.                         |\n|Science..Technology..Engineering....Mathematics    |\n|STEM                                               |\n|Transportation..Distribution...Logistics           |\n|Work.Experience.Handicapped                        |\n|Work.Experience.Handicapped..16.20..on.IEP.        |\n|Work.Experience.Career.Exploration..age.14.15.on.I |\n|Work.Experience.Disadvantaged                      |\n|Youth.Apprenticeship                               |\n|cte.achievement                                    |\n|english.learner                                    |\n|MCA.M                                              |\n|MCA.R                                              |\n|MCA.S                                              |\n|attended.ps                                        |\n|first.attend.ps                                    |\n|attended.ps.first.year                             |\n|attended.ps.years.hsgrad                           |\n|n.institutions                                     |\n|first.InstitutionSector                            |\n|ps.sector.1                                        |\n|ps.sector.2                                        |\n|ps.sector.3                                        |\n|ps.sector.4                                        |\n|ps.sector.5                                        |\n|ps.sector.6                                        |\n|ps.sector.7                                        |\n|ps.sector.8                                        |\n|ps.sector.9                                        |\n|ps.in.same.ruca                                    |\n|ps.in.same.edr                                     |\n|ps.in.same.pr                                      |\n|ps.in.MN                                           |\n|hs.grad.year                                       |\n|ps.attended.in.same.ruca                           |\n|ps.attended.in.same.edr                            |\n|ps.attended.in.same.pr                             |\n|ps.attended.in.MN                                  |\n|ps.grad                                            |\n|min.ps.grad.year                                   |\n|max.ps.grad.year                                   |\n|years.between.grads                                |\n|ps.grad.InstitutionSector                          |\n|highest.cred.level                                 |\n|ps.grad.in.same.ruca                               |\n|ps.grad.in.same.edr                                |\n|ps.grad.in.same.pr                                 |\n|ps.grad.in.MN                                      |\n|ps.grad.location                                   |\n|mn.emp.record.hs.grad.year                         |\n|mn.emp.record.hs.grad.year.2                       |\n|mn.emp.record.hs.grad.year.7                       |\n|meaningful.emp.hs.grad.year                        |\n|meaningful.emp.hs.grad.year.2                      |\n|meaningful.emp.hs.grad.year.7                      |\n|hs.grad.year.county.match                          |\n|hs.grad.year.2.county.match                        |\n|hs.grad.year.7.county.match                        |\n|hs.grad.year.edr.match                             |\n|hs.grad.year.2.edr.match                           |\n|hs.grad.year.7.edr.match                           |\n|hs.grad.year.region.match                          |\n|hs.grad.year.2.region.match                        |\n|hs.grad.year.7.region.match                        |\n|hs.grad.year.state.match                           |\n|hs.grad.year.2.state.match                         |\n|hs.grad.year.7.state.match                         |\n|ind.match.hs.grad.year                             |\n|ind.match.hs.grad.year.2                           |\n|ind.match.hs.grad.year.7                           |\n|avg.unemp.rate                                     |\n|wages.3year.avg                                    |\n|avg.wages.pct.state                                |\n|grad.year.10                                       |\n|grad.year.1                                        |\n|grad.year.5                                        |\n\n\n:::\n:::\n\n\n\n\n# Multivariate Confirmation Analysis: Non-College Completers in Northwest Minnesota\n\nThe primary purpose of this supplemental analysis is to examine workforce participation pathways among individuals who did not complete a postsecondary credential. Earlier sections of this analysis demonstrated that among the full Northwest Minnesota population, postsecondary attainment — particularly where and how a credential was earned — was the dominant mechanism associated with sustained regional employment. This section shifts attention to the population for whom that mechanism does not operate.\n\nAmong non-college completers, workforce participation pathways cannot be explained by credential depth, institutional sector, or graduation location. Instead, the descriptive and bivariate analyses conducted earlier identified high school career alignment (CTE), post-secondary attendance without completion, community type, and gender as the central differentiators of workforce outcomes in this population.\n\nTo strengthen confidence in those findings, a limited multivariate analysis is conducted using logistic regression. As in the full-population analysis, the goal is not causal inference or prediction, but confirmatory testing — specifically, whether the strongest bivariate relationships remain directionally consistent when key predictors are considered simultaneously.\n\nLogistic regression is used here as a confirmatory tool rather than the primary analytic framework.\n\n<br>\n\n# Methodology\n\n## Study Population\n\nThe analytic sample is restricted to individuals who graduated from a high school in Northwest Minnesota and did not complete a postsecondary credential. This restriction isolates workforce dynamics among high school graduates entering the labor market directly, with or without some post-secondary exposure.\n\n## Outcome Variable\n\nThe primary model predicts:\n\n-   **Meaningful employment — region** (binary outcome)\n\nThe dependent variable is coded as:\n\n-   1 = Meaningful employment in the Northwest Minnesota region\n-   0 = All other workforce outcomes (including meaningful employment elsewhere in Minnesota, not meaningful employment, and no Minnesota employment record)\n\nThis specification maintains consistency with earlier modeling while isolating mechanisms specific to the non-college completer population.\n\n## Independent Variables\n\nBecause postsecondary completion mechanisms are not applicable in this subgroup, the model focuses on high school preparation, structural background, and local labor market context identified as important in earlier analyses. Notably, the earlier bivariate analysis found that academic readiness measures (MCA scores) predicted out-of-region mobility rather than regional attachment, while CTE engagement was the most consistent and durable predictor of regional workforce attachment across all time points.\n\nPredictors include:\n\n-   **High school accomplishments**\n    -   `cte.achievement` — the strongest and most consistent predictor of regional workforce attachment identified in the bivariate analysis\n    -   `total.cte.courses.taken` — reinforces CTE achievement with a continuous dose-response measure\n    -   `attended.ps` — even without completion, post-secondary attendance showed meaningful associations with workforce outcomes\n    -   `MCA.M` — included as the primary academic readiness measure; expected to predict out-of-region rather than regional employment\n    -   `pseo.participant` — included to test whether early college exposure retains independent influence once other preparation variables are controlled\n-   **Demographic characteristics**\n    -   `Gender` — the strongest demographic predictor, with males consistently more likely to achieve regional meaningful employment\n    -   `RaceEthnicity` — included for equity considerations despite negligible overall association\n    -   `economic.status` — included as a structural disadvantage indicator\n    -   `SpecialEdStatus` — strongest demographic predictor at year 1 in the bivariate analysis\n-   **High school and local context**\n    -   `Dem_Desc` — the strongest high school characteristics predictor, with entirely urban non-completers showing dramatically higher disconnection rates\n    -   `avg.unemp.rate` — included with the explicit caveat that its counterintuitive direction likely reflects the North Dakota cross-border employment effect\n    -   `avg.wages.pct.state` — included as a complementary county-level economic context measure\n\nVariables are selected based on:\n\n1.  Strength of association in prior bivariate and persistence analyses\n2.  Conceptual plausibility within a non-college pathway\n3.  Policy relevance\n4.  Avoidance of redundancy\n\nPostsecondary completion variables are excluded by design.\n\n<br>\n\n# Analysis Approach\n\nThis multivariate analysis mirrors the structured confirmatory framework used in the full-population models but is adapted to the non-college completer subgroup and the specific findings of the Northwest Minnesota analysis.\n\n## Time-Based Modeling Strategy\n\nWorkforce attachment evolves over time. To capture this dynamic process, models are estimated separately at:\n\n-   **1 year after high school**\n-   **5 years after high school**\n-   **10 years after high school**\n\nThis staged approach allows examination of how mechanisms shift across early, mid-term, and longer-term workforce trajectories — a distinction that proved meaningful in the bivariate analysis, where several variables (particularly economic status, special education status, and PSEO participation) showed strong early associations that faded substantially over time.\n\n### Year 1: Immediate Labor Market Entry\n\nThe 1-year model captures the initial transition into the labor market. At this stage, high school preparation and career alignment are expected to exert the strongest influence. CTE exposure emerged as the strongest high school-level predictor at year 1 in the bivariate analysis, while post-secondary attendance had its largest association at this time point due to ongoing enrollment. The year 1 model tests whether these early preparation effects hold when structural and contextual factors are considered simultaneously.\n\n### Year 5: Stabilization Phase\n\nThe 5-year model reflects early career consolidation. The bivariate analysis showed that CTE's influence stabilized at this point while other variables — particularly economic status and PSEO participation — had largely attenuated. This model evaluates whether CTE retains its independent regional retention effect and whether gender and community type become more prominent as careers develop.\n\n### Year 10: Long-Term Embeddedness\n\nThe 10-year model captures longer-term workforce integration. The bivariate analysis suggested that MCA scores became more clearly associated with out-of-region employment by year 10, while CTE remained stable. This model tests whether local labor market context — county wages and unemployment — becomes increasingly dominant over time, and whether the North Dakota border effect continues to complicate interpretation of the unemployment rate variable.\n\n## Modeling Strategy\n\nWithin each time period, predictors are introduced in a structured sequence:\n\n### Model 1: Structural and Demographic Baseline\n\nIncludes demographic characteristics and community type:\n\n-   `RaceEthnicity`\n-   `economic.status`\n-   `SpecialEdStatus`\n-   `Gender`\n-   `Dem_Desc`\n\nThis baseline model evaluates whether structural background and community type independently differentiate regional workforce attachment prior to the inclusion of high school preparation variables. It also establishes whether the gender and urban/rural patterns identified in the bivariate analysis persist in a multivariate context.\n\n### Model 2: Add High School Accomplishments\n\nAdds the following to Model 1:\n\n-   `cte.achievement`\n-   `attended.ps`\n-   `MCA.M`\n-   `pseo.participant`\n\nThis is the core explanatory model. Key questions include:\n\n-   Does CTE retain its strong independent association with regional employment after controlling for demographics and community type?\n-   Does attended post-secondary add independent signal beyond CTE engagement?\n-   Do MCA scores show the expected negative association with regional employment, consistent with the out-of-region mobility pattern identified in the bivariate analysis?\n-   Do structural disadvantage effects (economic status, special education) attenuate once preparation variables are included?\n\n### Model 3: Add Local Labor Market Context\n\nAdds county-level economic context to Model 2:\n\n-   `avg.wages.pct.state`\n-   `avg.unemp.rate`\n\nKey questions include:\n\n-   Does the counterintuitive unemployment rate direction persist in a multivariate context, and does it attenuate the Dem_Desc effect once included?\n-   Do county wages add independent signal beyond community type?\n-   Do CTE and demographic effects remain stable once local economic context is accounted for?\n\nThis is the full confirmatory specification.\n\n## Evaluation Criteria\n\nResults will be reported using:\n\n-   Odds ratios\n-   95% confidence intervals\n-   Statistical significance levels\n-   Directional interpretation\n\nModel comparison metrics (AIC and pseudo R²) will be used to assess relative improvement across specifications, but emphasis will remain on coefficient magnitude and stability across time points and model specifications.\n\n## Interpretation Framework\n\nInterpretation will focus on:\n\n-   Whether CTE retains independent influence across all three time points — the central confirmatory question given its dominance in the bivariate analysis\n-   Whether gender and community type effects persist once preparation and economic context are controlled\n-   Whether the unemployment rate's counterintuitive direction is sustained in the multivariate context, providing further confirmation of the North Dakota border effect\n-   How mechanisms shift from Year 1 to Year 10, and whether structural or contextual factors become increasingly dominant over time\n\nFindings will be described as associations holding other included variables constant. No causal claims will be made.\n\n<br>\n\n## Conceptual Focus\n\nFor non-college completers in Northwest Minnesota, this time-structured modeling framework evaluates three evolving mechanisms:\n\n1.  **Career alignment at labor market entry** — captured primarily through CTE engagement and post-secondary attendance\n2.  **Structural advantage or disadvantage shaping early stability** — captured through demographic characteristics and community type\n3.  **Local economic opportunity structures influencing long-term embeddedness** — captured through county-level wage and unemployment measures, with explicit attention to the North Dakota border effect\n\nTogether, these models clarify whether sustained regional employment among non-college completers in Northwest Minnesota reflects early career alignment, structural inequality, local economic context, or a combination of all three — and whether the relative importance of these mechanisms shifts across the first decade after high school.\n\n<br>\n\n# Prep data\n\nThe first thing I need to do is setup my dataset for modeling. I'm going to create the workforce participation into a binary and will use grad.year.1, grad.year.5 and grad.year.10 as my modeling year.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmaster.model.1 <- master %>%\n  filter(ps.grad == \"No\") %>%\n  select(PersonID, RaceEthnicity, economic.status, SpecialEdStatus, Gender, Dem_Desc, avg.wages.pct.state, avg.unemp.rate, pseo.participant, cte.achievement, MCA.M, attended.ps, grad.year.1) %>%\n  filter(grad.year.1 != \"After 2023\",\n         grad.year.1 != \"Attending ps\",\n         RaceEthnicity != \"Unknown\") %>%\n  mutate(grad.year.1 = ifelse(grad.year.1 %in% c(\"Meaningful emp region\", \"Meaningful emp County\", \"Meaningful emp EDR\"), \"Meaningful emp region\", grad.year.1),\n         grad.year.1 = str_replace(grad.year.1, \", not attending ps\", \"\"),\n         grad.year.1 = ifelse(grad.year.1 == \"Meaningful emp region\", 1, 0),\n         RaceEthnicity = fct_relevel(RaceEthnicity, \"White\"),\n         Gender = fct_relevel(Gender, \"M\"),\n         cte.achievement = fct_relevel(cte.achievement, \"No CTE\"),\n         attended.ps = fct_relevel(attended.ps, \"No\"),\n         pseo.participant = ifelse(is.na(pseo.participant), 0, pseo.participant),\n         pseo.participant = as.character(pseo.participant),\n         pseo.participant = fct_relevel(pseo.participant, \"0\"),\n         economic.status = as.character(economic.status),\n         economic.status = fct_relevel(economic.status, \"0\"),\n         SpecialEdStatus = as.character(SpecialEdStatus),\n         SpecialEdStatus = fct_relevel(SpecialEdStatus, \"0\"),\n         Dem_Desc = fct_relevel(Dem_Desc, \"Entirely rural\"))\n\nkable(head(master.model.1))\n```\n\n::: {.cell-output-display}\n\n\n| PersonID|RaceEthnicity |economic.status |SpecialEdStatus |Gender |Dem_Desc             | avg.wages.pct.state| avg.unemp.rate|pseo.participant |cte.achievement               | MCA.M|attended.ps | grad.year.1|\n|--------:|:-------------|:---------------|:---------------|:------|:--------------------|-------------------:|--------------:|:----------------|:-----------------------------|-----:|:-----------|-----------:|\n|  2500266|White         |0               |1               |M      |Urban/town/rural mix |           0.8327785|       5.166667|0                |CTE Concentrator or Completor |     1|No          |           1|\n|  9921622|White         |0               |0               |M      |Town/rural mix       |           0.7917168|       9.333333|0                |CTE Concentrator or Completor |     3|No          |           1|\n| 11507369|White         |0               |0               |M      |Urban/town/rural mix |           0.8331740|       4.433333|1                |CTE Participant               |     4|No          |           0|\n|  1668126|White         |0               |0               |F      |Town/rural mix       |           0.8313067|       4.300000|0                |CTE Concentrator or Completor |     3|Yes         |           0|\n|  5684086|White         |0               |0               |M      |Town/rural mix       |           0.6569517|      12.133333|0                |CTE Concentrator or Completor |     1|No          |           1|\n|  4518802|White         |0               |0               |F      |Urban/town/rural mix |           0.8217433|       4.266667|0                |CTE Concentrator or Completor |     3|Yes         |           0|\n\n\n:::\n\n```{.r .cell-code}\nkable(names(master.model.1))\n```\n\n::: {.cell-output-display}\n\n\n|x                   |\n|:-------------------|\n|PersonID            |\n|RaceEthnicity       |\n|economic.status     |\n|SpecialEdStatus     |\n|Gender              |\n|Dem_Desc            |\n|avg.wages.pct.state |\n|avg.unemp.rate      |\n|pseo.participant    |\n|cte.achievement     |\n|MCA.M               |\n|attended.ps         |\n|grad.year.1         |\n\n\n:::\n\n```{.r .cell-code}\nmaster.model.5 <- master %>%\n  filter(ps.grad == \"No\") %>%\n  select(PersonID, RaceEthnicity, economic.status, SpecialEdStatus, Gender, Dem_Desc, avg.wages.pct.state, avg.unemp.rate, pseo.participant, cte.achievement, MCA.M, attended.ps, grad.year.5) %>%\n  filter(grad.year.5 != \"After 2023\",\n         grad.year.5 != \"Attending ps\",\n         RaceEthnicity != \"Unknown\") %>%\n  mutate(grad.year.5 = ifelse(grad.year.5 %in% c(\"Meaningful emp region\", \"Meaningful emp County\", \"Meaningful emp EDR\"), \"Meaningful emp region\", grad.year.5),\n         grad.year.5 = str_replace(grad.year.5, \", not attending ps\", \"\"),\n         grad.year.5 = ifelse(grad.year.5 == \"Meaningful emp region\", 1, 0),\n         RaceEthnicity = fct_relevel(RaceEthnicity, \"White\"),\n         Gender = fct_relevel(Gender, \"M\"),\n         cte.achievement = fct_relevel(cte.achievement, \"No CTE\"),\n         attended.ps = fct_relevel(attended.ps, \"No\"),\n         pseo.participant = ifelse(is.na(pseo.participant), 0, pseo.participant),\n         pseo.participant = as.character(pseo.participant),\n         pseo.participant = fct_relevel(pseo.participant, \"0\"),\n         economic.status = as.character(economic.status),\n         economic.status = fct_relevel(economic.status, \"0\"),\n         SpecialEdStatus = as.character(SpecialEdStatus),\n         SpecialEdStatus = fct_relevel(SpecialEdStatus, \"0\"),\n         Dem_Desc = fct_relevel(Dem_Desc, \"Entirely rural\"))\n\n\nkable(head(master.model.5))\n```\n\n::: {.cell-output-display}\n\n\n| PersonID|RaceEthnicity |economic.status |SpecialEdStatus |Gender |Dem_Desc             | avg.wages.pct.state| avg.unemp.rate|pseo.participant |cte.achievement               | MCA.M|attended.ps | grad.year.5|\n|--------:|:-------------|:---------------|:---------------|:------|:--------------------|-------------------:|--------------:|:----------------|:-----------------------------|-----:|:-----------|-----------:|\n|  2500266|White         |0               |1               |M      |Urban/town/rural mix |           0.8327785|       5.166667|0                |CTE Concentrator or Completor |     1|No          |           0|\n|  9533044|White         |0               |0               |F      |Town/rural mix       |           1.0247095|       5.233333|0                |CTE Concentrator or Completor |     2|Yes         |           0|\n| 11507369|White         |0               |0               |M      |Urban/town/rural mix |           0.8331740|       4.433333|1                |CTE Participant               |     4|No          |           1|\n|  1668126|White         |0               |0               |F      |Town/rural mix       |           0.8313067|       4.300000|0                |CTE Concentrator or Completor |     3|Yes         |           1|\n|  5684086|White         |0               |0               |M      |Town/rural mix       |           0.6569517|      12.133333|0                |CTE Concentrator or Completor |     1|No          |           1|\n|  5442452|White         |0               |0               |M      |Town/rural mix       |           0.9691107|       6.133333|0                |CTE Concentrator or Completor |     3|Yes         |           1|\n\n\n:::\n\n```{.r .cell-code}\nkable(names(master.model.5))\n```\n\n::: {.cell-output-display}\n\n\n|x                   |\n|:-------------------|\n|PersonID            |\n|RaceEthnicity       |\n|economic.status     |\n|SpecialEdStatus     |\n|Gender              |\n|Dem_Desc            |\n|avg.wages.pct.state |\n|avg.unemp.rate      |\n|pseo.participant    |\n|cte.achievement     |\n|MCA.M               |\n|attended.ps         |\n|grad.year.5         |\n\n\n:::\n\n```{.r .cell-code}\nmaster.model.10 <- master %>%\n  filter(ps.grad == \"No\",\n         RaceEthnicity != \"Unknown\",\n         grad.year.10 != \"Attending ps\") %>%\n  select(PersonID, RaceEthnicity, economic.status, SpecialEdStatus, Gender, Dem_Desc, avg.wages.pct.state, avg.unemp.rate, pseo.participant, cte.achievement, MCA.M, attended.ps, grad.year.10) %>%\n  filter(grad.year.10 != \"After 2023\",\n         grad.year.10 != \"Attending ps\") %>%\n  mutate(grad.year.10 = ifelse(grad.year.10 %in% c(\"Meaningful emp region\", \"Meaningful emp County\", \"Meaningful emp EDR\"), \"Meaningful emp region\", grad.year.10),\n         grad.year.10 = str_replace(grad.year.10, \", not attending ps\", \"\"),\n         grad.year.10 = ifelse(grad.year.10 == \"Meaningful emp region\", 1, 0),\n         RaceEthnicity = fct_relevel(RaceEthnicity, \"White\"),\n         Gender = fct_relevel(Gender, \"M\"),\n         cte.achievement = fct_relevel(cte.achievement, \"No CTE\"),\n         attended.ps = fct_relevel(attended.ps, \"No\"),\n         pseo.participant = ifelse(is.na(pseo.participant), 0, pseo.participant),\n         pseo.participant = as.character(pseo.participant),\n         pseo.participant = fct_relevel(pseo.participant, \"0\"),\n         economic.status = as.character(economic.status),\n         economic.status = fct_relevel(economic.status, \"0\"),\n         SpecialEdStatus = as.character(SpecialEdStatus),\n         SpecialEdStatus = fct_relevel(SpecialEdStatus, \"0\"),\n         Dem_Desc = fct_relevel(Dem_Desc, \"Entirely rural\"))\n\n\nkable(head(master.model.10))\n```\n\n::: {.cell-output-display}\n\n\n| PersonID|RaceEthnicity |economic.status |SpecialEdStatus |Gender |Dem_Desc             | avg.wages.pct.state| avg.unemp.rate|pseo.participant |cte.achievement               | MCA.M|attended.ps | grad.year.10|\n|--------:|:-------------|:---------------|:---------------|:------|:--------------------|-------------------:|--------------:|:----------------|:-----------------------------|-----:|:-----------|------------:|\n|  2500266|White         |0               |1               |M      |Urban/town/rural mix |           0.8327785|       5.166667|0                |CTE Concentrator or Completor |     1|No          |            1|\n|  9533044|White         |0               |0               |F      |Town/rural mix       |           1.0247095|       5.233333|0                |CTE Concentrator or Completor |     2|Yes         |            0|\n|  5684086|White         |0               |0               |M      |Town/rural mix       |           0.6569517|      12.133333|0                |CTE Concentrator or Completor |     1|No          |            1|\n|  5442452|White         |0               |0               |M      |Town/rural mix       |           0.9691107|       6.133333|0                |CTE Concentrator or Completor |     3|Yes         |            1|\n|  8583058|White         |0               |0               |M      |Urban/town/rural mix |           0.8327785|       5.166667|0                |CTE Concentrator or Completor |     1|Yes         |            0|\n|  3675888|White         |0               |0               |F      |Entirely rural       |           0.8242080|       6.666667|0                |No CTE                        |     4|No          |            0|\n\n\n:::\n\n```{.r .cell-code}\nkable(names(master.model.10))\n```\n\n::: {.cell-output-display}\n\n\n|x                   |\n|:-------------------|\n|PersonID            |\n|RaceEthnicity       |\n|economic.status     |\n|SpecialEdStatus     |\n|Gender              |\n|Dem_Desc            |\n|avg.wages.pct.state |\n|avg.unemp.rate      |\n|pseo.participant    |\n|cte.achievement     |\n|MCA.M               |\n|attended.ps         |\n|grad.year.10        |\n\n\n:::\n:::\n\n\n\n\nWe now have 21,268 individuals to model with 11 variables not including `grad.year.5`.\n\n<br>\n\n# Modeling - `grad.year.1`\n\n## Model 1 — Year 1: Structural and Demographic Baseline\n\nModel 1 establishes the baseline associations between demographic characteristics and community type with meaningful regional employment one year after high school, prior to the inclusion of any high school preparation variables. The model shows modest improvement over the null (AIC = 22,040, residual deviance = 22,020 vs. null deviance = 22,280), consistent with expectations that structural factors alone explain only a limited portion of regional workforce attachment.\n\n**Gender** and **special education status** show the strongest associations in this baseline model:\n\n-   Females have approximately 19% lower odds of meaningful regional employment relative to males (OR = 0.813, p \\< .001), consistent with the male-dominated industry composition of the NW region identified throughout the bivariate analysis\n-   Students with special education status have approximately 21% lower odds of meaningful regional employment relative to non-special education students (OR = 0.791, p \\< .001)\n\n**Community type** shows meaningful and expected associations:\n\n-   Entirely urban non-completers have approximately 39% lower odds of meaningful regional employment relative to entirely rural students (OR = 0.614, p \\< .001), the strongest single association in the model and consistent with the striking urban disconnection pattern identified throughout the earlier analyses\n-   Town/rural mix students have approximately 24% higher odds of regional employment relative to entirely rural students (OR = 1.244, p \\< .001), reinforcing their consistently favorable workforce attachment pattern\n-   Urban/town/rural mix students also show modestly higher odds (OR = 1.180, p = .012)\n\n**Race/ethnicity** shows mixed results:\n\n-   Asian/PI non-completers have substantially lower odds of regional employment relative to White students (OR = 0.413, p \\< .001), the largest racial/ethnic disparity in the model\n-   Hispanic non-completers show significantly lower odds (OR = 0.805, p = .012)\n-   American Indian and Black non-completers show lower odds but do not reach statistical significance at the .01 level\n\n**Economic status** shows no significant independent association with regional employment at year 1 (OR = 0.989, p = .752), consistent with the negligible bivariate finding.\n\n*Model note: The baseline model confirms the structural patterns identified in the bivariate analysis — gender, special education status, and community type are the dominant structural associates of regional workforce attachment at year 1. The introduction of high school preparation variables in Model 2 will test whether these associations persist or attenuate once career alignment is accounted for.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- glm(\n  grad.year.1 ~\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    Gender +\n    Dem_Desc,\n  family = binomial,\n  data = master.model.1\n)\n\nmodel1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = grad.year.1 ~ RaceEthnicity + economic.status + \n    SpecialEdStatus + Gender + Dem_Desc, family = binomial, data = master.model.1)\n\nCoefficients:\n                 (Intercept)               RaceEthnicityAI  \n                    -1.13970                      -0.08489  \n       RaceEthnicityAsian/PI            RaceEthnicityBlack  \n                    -0.88519                      -0.23810  \n       RaceEthnicityHispanic              economic.status1  \n                    -0.21673                      -0.01108  \n            SpecialEdStatus1                       GenderF  \n                    -0.23447                      -0.20703  \n      Dem_DescEntirely urban        Dem_DescTown/rural mix  \n                    -0.48729                       0.21828  \nDem_DescUrban/town/rural mix  \n                     0.16534  \n\nDegrees of Freedom: 20700 Total (i.e. Null);  20690 Residual\nNull Deviance:\t    22280 \nResidual Deviance: 22020 \tAIC: 22040\n```\n\n\n:::\n\n```{.r .cell-code}\nor_plot <- tidy(model1, conf.int = TRUE, exponentiate = TRUE) %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(\n    # Make labels nicer (edit these replacements to match your exact factor labels)\n    term = str_replace_all(term, c(\n      \"RaceEthnicity\" = \"Race: \",\n      \"economic.status\" = \"Economic status: \",\n      \"Gender\" = \"Gender: \",\n      \"SpecialEdStatus\" = \"Special Ed: \",\n      \"Dem_Desc\" = \"Dem_Desc: \"\n    )),\n    # Put most important effects near the top (optional: tweak ordering later)\n    term = fct_reorder(term, estimate)\n  )\n\nggplot(or_plot, aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\") +\n  geom_vline(xintercept = c(0.5, 0.75, 1.25, 1.5, 2),\n             color = \"grey85\") +\n  geom_point() +\n  geom_errorbar(\n    aes(xmin = conf.low, xmax = conf.high),\n    orientation = \"y\",\n    width = 0.2\n  ) +\n  scale_x_log10(\n    breaks = c(0.5, 0.75, 1, 1.25, 1.5, 2),\n    labels = c(\"0.5\", \"0.75\", \"1.0\", \"1.25\", \"1.5\", \"2.0\")\n  ) +\n  theme_line +\n  labs(\n    x = \"Odds ratio (log scale)\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](analysis_multivariate_confirmation_non_college_grads_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\n<br>\n\n## Model 2 — Year 1: Adding High School Accomplishments\n\nModel 2 introduces high school preparation variables alongside the structural baseline, producing substantial improvement in model fit (AIC = 20,700 vs. 22,040 in Model 1, residual deviance = 20,670 vs. 22,020). Note that 1,441 observations are lost due to missing MCA scores, so direct AIC comparison with Model 1 should be interpreted with some caution.\n\n**Attended post-secondary** and **CTE achievement** emerge as the two strongest associations in the model:\n\n-   Non-completers who attended post-secondary have approximately 69% higher odds of meaningful regional employment relative to those who never attended (OR = 1.690, p \\< .001), the largest single association in the model. This finding is notable — even without completing a credential, post-secondary attendance is strongly associated with regional workforce attachment at year 1\n-   CTE concentrators and completers have approximately 70% higher odds of meaningful regional employment relative to non-CTE students (OR = 1.695, p \\< .001), nearly identical in magnitude to attended post-secondary and retaining robust independent influence net of all other variables\n-   CTE participants have approximately 31% higher odds relative to non-CTE students (OR = 1.314, p \\< .001), confirming the dose-response pattern identified throughout the bivariate analysis\n\n**Community type** associations strengthen with the addition of preparation variables:\n\n-   Entirely urban non-completers retain approximately 40% lower odds of regional employment relative to entirely rural students (OR = 0.598, p \\< .001), nearly unchanged from Model 1, indicating that community type operates independently of high school preparation\n-   Town/rural mix students show stronger higher odds (OR = 1.328, p \\< .001) compared to Model 1 (OR = 1.244), suggesting that preparation variables reveal a slightly stronger geographic effect once controlled\n-   Urban/town/rural mix students also show higher odds (OR = 1.256, p = .001)\n\n**PSEO participation** shows a significant negative association with regional employment (OR = 0.763, p \\< .001), consistent with the earlier bivariate finding that PSEO is associated with post-secondary continuation and out-of-region mobility rather than regional workforce attachment\n\n**Gender and special education status** attenuate compared to Model 1:\n\n-   The gender gap narrows from OR = 0.813 in Model 1 to OR = 0.869 (p \\< .001), suggesting that some of the gender gap in regional employment is explained by differences in high school preparation and post-secondary attendance\n-   Special education status attenuates more substantially, from OR = 0.791 in Model 1 to OR = 0.904 (p = .019), indicating that preparation variables explain a meaningful portion of this structural disadvantage, though the association remains significant\n\n**MCA Math** shows no significant independent association with regional employment at year 1 (OR = 1.021, p = .245), consistent with the bivariate finding that academic proficiency does not strongly differentiate regional from non-regional outcomes in the short term\n\n**Race/ethnicity and economic status** attenuate further compared to Model 1:\n\n-   Hispanic non-completers are no longer significantly associated with lower regional employment (OR = 0.907, p = .283), suggesting their earlier disadvantage was partially explained by preparation and attendance differences\n-   Asian/PI non-completers retain significantly lower odds (OR = 0.506, p = .001)\n-   Economic status remains non-significant (OR = 0.971, p = .424)\n\n*Model note: The addition of high school preparation variables substantially improves model fit and confirms both CTE engagement and post-secondary attendance as the dominant independent associates of regional workforce attachment at year 1. The stability of community type effects and the partial attenuation of gender and special education associations suggest preparation and structural factors operate through partially distinct mechanisms. Model 3 will test whether local labor market context further explains remaining structural gaps.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- glm(\n  grad.year.1 ~\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    Gender +\n    Dem_Desc +\n    cte.achievement +\n    MCA.M +\n    pseo.participant +\n    attended.ps,\n  family = binomial,\n  data = master.model.1\n)\n\nmodel2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = grad.year.1 ~ RaceEthnicity + economic.status + \n    SpecialEdStatus + Gender + Dem_Desc + cte.achievement + MCA.M + \n    pseo.participant + attended.ps, family = binomial, data = master.model.1)\n\nCoefficients:\n                                 (Intercept)  \n                                  -1.7338787  \n                             RaceEthnicityAI  \n                                  -0.0004614  \n                       RaceEthnicityAsian/PI  \n                                  -0.6810841  \n                          RaceEthnicityBlack  \n                                  -0.2298242  \n                       RaceEthnicityHispanic  \n                                  -0.0974005  \n                            economic.status1  \n                                  -0.0290047  \n                            SpecialEdStatus1  \n                                  -0.1009744  \n                                     GenderF  \n                                  -0.1409621  \n                      Dem_DescEntirely urban  \n                                  -0.5138997  \n                      Dem_DescTown/rural mix  \n                                   0.2835156  \n                Dem_DescUrban/town/rural mix  \n                                   0.2280847  \ncte.achievementCTE Concentrator or Completor  \n                                   0.5277584  \n              cte.achievementCTE Participant  \n                                   0.2732860  \n                                       MCA.M  \n                                   0.0211136  \n                           pseo.participant1  \n                                  -0.2698880  \n                              attended.psYes  \n                                   0.5245666  \n\nDegrees of Freedom: 19259 Total (i.e. Null);  19244 Residual\n  (1441 observations deleted due to missingness)\nNull Deviance:\t    21260 \nResidual Deviance: 20670 \tAIC: 20700\n```\n\n\n:::\n\n```{.r .cell-code}\nor_plot <- tidy(model2, conf.int = TRUE, exponentiate = TRUE) %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(\n    # Make labels nicer (edit these replacements to match your exact factor labels)\n    term = str_replace_all(term, c(\n      \"RaceEthnicity\" = \"Race: \",\n      \"economic.status\" = \"Economic status: \",\n      \"SpecialEdStatus\" = \"Special Ed: \",\n      \"pseo.participant\" = \"PSEO: \",\n      \"cte.achievement\" = \"CTE: \",\n      \"MCA.R\" = \"MCA Reading\",\n      \"MCA.M\" = \"MCA Math\",\n      \"Dem_Desc\" = \"Dem_Desc: \",\n      \"Gender\" = \"Gender: \",\n      \"took.ACT\" = \"Took ACT: \"\n    )),\n    # Put most important effects near the top (optional: tweak ordering later)\n    term = fct_reorder(term, estimate)\n  )\n\nggplot(or_plot, aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\") +\n  geom_vline(xintercept = c(0.5, 0.75, 1.25, 1.5, 2),\n             color = \"grey85\") +\n  geom_point() +\n  geom_errorbar(\n    aes(xmin = conf.low, xmax = conf.high),\n    orientation = \"y\",\n    width = 0.2\n  ) +\n  scale_x_log10(\n    breaks = c(0.5, 0.75, 1, 1.25, 1.5, 2),\n    labels = c(\"0.5\", \"0.75\", \"1.0\", \"1.25\", \"1.5\", \"2.0\")\n  ) +\n  theme_line +\n  labs(\n    x = \"Odds ratio (log scale)\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](analysis_multivariate_confirmation_non_college_grads_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\n<br>\n\n## Model 3 — Year 1: Adding Local Labor Market Context\n\nModel 3 adds county-level unemployment rate and wages as a percent of state average to the full Model 2 specification. The addition of these two variables produces no meaningful improvement in model fit — AIC remains unchanged at 20,700 and residual deviance is essentially identical to Model 2 (20,670) — indicating that local labor market context adds no independent explanatory power to regional workforce attachment at year 1 beyond what is already captured by community type, preparation, and structural variables.\n\n**All core associations from Model 2 remain stable:**\n\n-   CTE concentrators and completers retain approximately 70% higher odds of regional employment (OR = 1.702, p \\< .001), essentially unchanged from Model 2 (OR = 1.695)\n-   Attended post-secondary retains approximately 69% higher odds (OR = 1.691, p \\< .001), unchanged from Model 2 (OR = 1.690)\n-   CTE participants retain approximately 31% higher odds (OR = 1.311, p \\< .001)\n-   PSEO participation retains its negative association (OR = 0.762, p \\< .001)\n-   Community type associations remain stable — entirely urban non-completers retain approximately 38% lower odds (OR = 0.620, p \\< .001) and town/rural mix students retain approximately 33% higher odds (OR = 1.325, p \\< .001)\n-   Gender and special education status associations are essentially unchanged from Model 2\n\n**Neither labor market variable shows a significant independent association:**\n\n-   Average unemployment rate shows no significant association with regional employment at year 1 (OR = 1.008, p = .512), consistent with the counterintuitive and ambiguous pattern identified in the bivariate analysis\n-   Average wages as a percent of state average also shows no significant association (OR = 1.469, p = .074), though the direction is positive — higher wage counties are modestly associated with higher regional employment odds\n\n**Race/ethnicity and economic status** remain unchanged from Model 2 — Asian/PI non-completers retain significantly lower odds (OR = 0.507, p = .001) and economic status remains non-significant (OR = 0.972, p = .434)\n\n*Model note: The addition of local labor market context variables adds no meaningful explanatory power at year 1, confirming that regional workforce attachment in the immediate post-high school period is driven primarily by high school preparation — particularly CTE engagement and post-secondary attendance — and structural characteristics rather than local economic conditions. The stability of all Model 2 associations across Model 3 strengthens confidence in the core findings. The counterintuitive unemployment rate direction seen in the bivariate analysis does not persist as a significant association in the multivariate context, suggesting it was largely a compositional artifact rather than an independent mechanism.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- glm(\n  grad.year.1 ~\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    Gender +\n    Dem_Desc +\n    cte.achievement +\n    MCA.M +\n    pseo.participant +\n    attended.ps +\n    avg.unemp.rate +\n    avg.wages.pct.state,\n  family = binomial,\n  data = master.model.1\n)\n\nmodel3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = grad.year.1 ~ RaceEthnicity + economic.status + \n    SpecialEdStatus + Gender + Dem_Desc + cte.achievement + MCA.M + \n    pseo.participant + attended.ps + avg.unemp.rate + avg.wages.pct.state, \n    family = binomial, data = master.model.1)\n\nCoefficients:\n                                 (Intercept)  \n                                   -2.098520  \n                             RaceEthnicityAI  \n                                    0.026352  \n                       RaceEthnicityAsian/PI  \n                                   -0.678547  \n                          RaceEthnicityBlack  \n                                   -0.225416  \n                       RaceEthnicityHispanic  \n                                   -0.097398  \n                            economic.status1  \n                                   -0.028394  \n                            SpecialEdStatus1  \n                                   -0.102674  \n                                     GenderF  \n                                   -0.140438  \n                      Dem_DescEntirely urban  \n                                   -0.478443  \n                      Dem_DescTown/rural mix  \n                                    0.281509  \n                Dem_DescUrban/town/rural mix  \n                                    0.221947  \ncte.achievementCTE Concentrator or Completor  \n                                    0.531871  \n              cte.achievementCTE Participant  \n                                    0.270489  \n                                       MCA.M  \n                                    0.020450  \n                           pseo.participant1  \n                                   -0.272124  \n                              attended.psYes  \n                                    0.525361  \n                              avg.unemp.rate  \n                                    0.007655  \n                         avg.wages.pct.state  \n                                    0.384402  \n\nDegrees of Freedom: 19259 Total (i.e. Null);  19242 Residual\n  (1441 observations deleted due to missingness)\nNull Deviance:\t    21260 \nResidual Deviance: 20670 \tAIC: 20700\n```\n\n\n:::\n\n```{.r .cell-code}\nor_plot <- tidy(model3, conf.int = TRUE, exponentiate = TRUE) %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(\n    # Make labels nicer (edit these replacements to match your exact factor labels)\n    term = str_replace_all(term, c(\n      \"RaceEthnicity\" = \"Race: \",\n      \"economic.status\" = \"Economic status: \",\n      \"SpecialEdStatus\" = \"Special Ed: \",\n      \"pseo.participant\" = \"PSEO: \",\n      \"cte.achievement\" = \"CTE: \",\n      \"MCA.R\" = \"MCA Reading\",\n      \"MCA.M\" = \"MCA Math\",\n      \"Dem_Desc\" = \"Dem_Desc: \",\n      \"Gender\" = \"Gender: \",\n      \"took.ACT\" = \"Took ACT: \",\n      \"avg.unemp.rate\" = \"Avg unemp rate\",\n      \"avg.wages.pct.state\" = \"Avg wages pct state\"\n    )),\n    # Put most important effects near the top (optional: tweak ordering later)\n    term = fct_reorder(term, estimate)\n  )\n\nggplot(or_plot, aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\") +\n  geom_vline(xintercept = c(0.5, 0.75, 1.25, 1.5, 2),\n             color = \"grey85\") +\n  geom_point() +\n  geom_errorbar(\n    aes(xmin = conf.low, xmax = conf.high),\n    orientation = \"y\",\n    width = 0.2\n  ) +\n  scale_x_log10(\n    breaks = c(0.5, 0.75, 1, 1.25, 1.5, 2),\n    labels = c(\"0.5\", \"0.75\", \"1.0\", \"1.25\", \"1.5\", \"2.0\")\n  ) +\n  theme_line +\n  labs(\n    x = \"Odds ratio (log scale)\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](analysis_multivariate_confirmation_non_college_grads_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n<br>\n\n# Modeling - `grad.year.5`\n\n## Model 1 — Year 5: Structural and Demographic Baseline\n\nModel 1 establishes the baseline associations between demographic characteristics and community type with meaningful regional employment five years after high school, prior to the inclusion of any high school preparation variables. The model shows modest improvement over the null (AIC = 24,080, residual deviance = 24,050 vs. null deviance = 24,500), consistent with expectations that structural factors alone explain only a limited portion of regional workforce attachment.\n\n**Gender** shows the strongest demographic association in the model and strengthens compared to year 1:\n\n-   Females have approximately 25% lower odds of meaningful regional employment relative to males (OR = 0.746, p \\< .001), a larger gap than at year 1 (OR = 0.813), suggesting the gender disparity in regional workforce attachment widens over time\n\n**Community type** shows stronger associations at year 5 than at year 1:\n\n-   Entirely urban non-completers have approximately 53% lower odds of meaningful regional employment relative to entirely rural students (OR = 0.469, p \\< .001), a substantially larger gap than at year 1 (OR = 0.614), indicating that the urban penalty for regional workforce attachment grows over time\n-   Town/rural mix students show modestly higher odds (OR = 1.134, p = .019), though the advantage is smaller than at year 1 (OR = 1.244)\n-   Urban/town/rural mix students show no significant association at year 5 (OR = 1.037, p = .542), unlike year 1\n\n**Race/ethnicity** shows stronger and broader associations at year 5 compared to year 1:\n\n-   Black non-completers now show substantially lower odds of regional employment relative to White students (OR = 0.461, p \\< .001), a much stronger association than at year 1 where the effect was non-significant\n-   Hispanic non-completers show significantly lower odds (OR = 0.597, p \\< .001), also stronger than at year 1 (OR = 0.805)\n-   Asian/PI non-completers retain substantially lower odds (OR = 0.484, p \\< .001)\n-   American Indian non-completers now show a marginally significant association (OR = 0.891, p = .049)\n\n**Special education status** shows a weaker association at year 5 than at year 1:\n\n-   Students with special education status have approximately 9% lower odds of meaningful regional employment (OR = 0.914, p = .017), a substantially smaller gap than at year 1 (OR = 0.791), consistent with the bivariate finding that special education status is most consequential in the immediate post-high school period\n\n**Economic status** shows no significant independent association with regional employment at year 5 (OR = 1.026, p = .434), consistent with year 1 findings.\n\n*Model note: The year 5 baseline model reveals two important shifts from year 1 — the gender gap and urban penalty both widen over time, while the special education disadvantage attenuates. Racial and ethnic disparities are broader and stronger at year 5, suggesting these gaps grow rather than narrow as careers develop. The introduction of high school preparation variables in Model 2 will test whether these structural patterns persist once career alignment is accounted for.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- glm(\n  grad.year.5 ~\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    Gender +\n    Dem_Desc,\n  family = binomial,\n  data = master.model.5\n)\n\nmodel1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = grad.year.5 ~ RaceEthnicity + economic.status + \n    SpecialEdStatus + Gender + Dem_Desc, family = binomial, data = master.model.5)\n\nCoefficients:\n                 (Intercept)               RaceEthnicityAI  \n                    -0.85564                      -0.11551  \n       RaceEthnicityAsian/PI            RaceEthnicityBlack  \n                    -0.72600                      -0.77378  \n       RaceEthnicityHispanic              economic.status1  \n                    -0.51620                       0.02580  \n            SpecialEdStatus1                       GenderF  \n                    -0.09023                      -0.29343  \n      Dem_DescEntirely urban        Dem_DescTown/rural mix  \n                    -0.75713                       0.12542  \nDem_DescUrban/town/rural mix  \n                     0.03672  \n\nDegrees of Freedom: 21267 Total (i.e. Null);  21257 Residual\nNull Deviance:\t    24500 \nResidual Deviance: 24050 \tAIC: 24080\n```\n\n\n:::\n\n```{.r .cell-code}\nor_plot <- tidy(model1, conf.int = TRUE, exponentiate = TRUE) %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(\n    # Make labels nicer (edit these replacements to match your exact factor labels)\n    term = str_replace_all(term, c(\n      \"RaceEthnicity\" = \"Race: \",\n      \"economic.status\" = \"Economic status: \",\n      \"Gender\" = \"Gender: \",\n      \"SpecialEdStatus\" = \"Special Ed: \",\n      \"Dem_Desc\" = \"Dem_Desc: \"\n    )),\n    # Put most important effects near the top (optional: tweak ordering later)\n    term = fct_reorder(term, estimate)\n  )\n\nggplot(or_plot, aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\") +\n  geom_vline(xintercept = c(0.5, 0.75, 1.25, 1.5, 2),\n             color = \"grey85\") +\n  geom_point() +\n  geom_errorbar(\n    aes(xmin = conf.low, xmax = conf.high),\n    orientation = \"y\",\n    width = 0.2\n  ) +\n  scale_x_log10(\n    breaks = c(0.5, 0.75, 1, 1.25, 1.5, 2),\n    labels = c(\"0.5\", \"0.75\", \"1.0\", \"1.25\", \"1.5\", \"2.0\")\n  ) +\n  theme_line +\n  labs(\n    x = \"Odds ratio (log scale)\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](analysis_multivariate_confirmation_non_college_grads_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n<br>\n\n## Model 2 — Year 5: Adding High School Accomplishments\n\nModel 2 introduces high school preparation variables alongside the structural baseline, producing meaningful improvement in model fit (AIC = 22,910 vs. 24,080 in Model 1, residual deviance = 22,880 vs. 24,050). Note that 1,330 observations are lost due to missing MCA scores, so direct AIC comparison with Model 1 should be interpreted with some caution.\n\n**CTE achievement** emerges as the dominant associate at year 5, with attended post-secondary losing its earlier influence:\n\n-   CTE concentrators and completers have approximately 62% higher odds of meaningful regional employment relative to non-CTE students (OR = 1.620, p \\< .001), retaining robust independent influence net of all demographic and community type variables, though slightly attenuated from year 1 (OR = 1.695)\n-   CTE participants have approximately 38% higher odds relative to non-CTE students (OR = 1.377, p \\< .001), somewhat stronger than at year 1 (OR = 1.314), suggesting even moderate CTE engagement has a growing influence on regional attachment over time\n-   Attended post-secondary is no longer significantly associated with regional employment at year 5 (OR = 1.048, p = .158), a striking contrast to year 1 where it was the strongest associate in the model (OR = 1.690). This confirms that post-secondary attendance provides a short-term but not durable boost to regional workforce attachment among non-completers\n\n**Community type** associations remain strong and largely unchanged from Model 1 at year 5:\n\n-   Entirely urban non-completers retain approximately 53% lower odds of regional employment relative to entirely rural students (OR = 0.467, p \\< .001), essentially unchanged from the year 5 baseline model, again indicating that community type operates independently of high school preparation\n-   Town/rural mix students retain modestly higher odds (OR = 1.162, p = .006)\n-   Urban/town/rural mix students remain non-significant (OR = 1.053, p = .404)\n\n**PSEO participation** retains a significant negative association with regional employment (OR = 0.836, p \\< .001), though the magnitude is smaller than at year 1 (OR = 0.762), suggesting its out-of-region mobility effect moderates somewhat over time\n\n**Gender** attenuates but remains strongly significant:\n\n-   Females have approximately 21% lower odds of meaningful regional employment relative to males (OR = 0.795, p \\< .001), compared to 25% lower odds in the year 5 baseline model, indicating that preparation variables explain some but not all of the gender gap\n\n**Special education status** fully attenuates at year 5:\n\n-   The special education association is no longer significant (OR = 0.969, p = .453), consistent with the bivariate finding that special education status primarily shapes early transitions rather than longer-term workforce trajectories\n\n**Race/ethnicity** disparities persist and remain substantial even after controlling for preparation variables:\n\n-   Black non-completers retain approximately 49% lower odds of regional employment relative to White students (OR = 0.507, p \\< .001)\n-   Hispanic non-completers retain approximately 32% lower odds (OR = 0.685, p \\< .001)\n-   Asian/PI non-completers retain approximately 39% lower odds (OR = 0.611, p = .009)\n-   American Indian non-completers are no longer significant (OR = 0.937, p = .287)\n\n**MCA Math** remains non-significant at year 5 (OR = 0.987, p = .431), and notably the direction reverses slightly compared to year 1, though the effect is negligible\n\n**Economic status** remains non-significant (OR = 0.982, p = .596)\n\n*Model note: The year 5 Model 2 reveals an important shift from year 1 — CTE engagement becomes the clear dominant associate of regional workforce attachment while post-secondary attendance loses its influence entirely. The persistence of racial and ethnic disparities net of preparation variables is notable and suggests structural inequities operating beyond high school characteristics. Model 3 will test whether local labor market context explains any of the remaining variation.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- glm(\n  grad.year.5 ~\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    Gender +\n    Dem_Desc +\n    cte.achievement +\n    MCA.M +\n    pseo.participant +\n    attended.ps,\n  family = binomial,\n  data = master.model.5\n)\n\nmodel2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = grad.year.5 ~ RaceEthnicity + economic.status + \n    SpecialEdStatus + Gender + Dem_Desc + cte.achievement + MCA.M + \n    pseo.participant + attended.ps, family = binomial, data = master.model.5)\n\nCoefficients:\n                                 (Intercept)  \n                                    -1.15382  \n                             RaceEthnicityAI  \n                                    -0.06491  \n                       RaceEthnicityAsian/PI  \n                                    -0.49278  \n                          RaceEthnicityBlack  \n                                    -0.67870  \n                       RaceEthnicityHispanic  \n                                    -0.37826  \n                            economic.status1  \n                                    -0.01806  \n                            SpecialEdStatus1  \n                                    -0.03136  \n                                     GenderF  \n                                    -0.22921  \n                      Dem_DescEntirely urban  \n                                    -0.76072  \n                      Dem_DescTown/rural mix  \n                                     0.15051  \n                Dem_DescUrban/town/rural mix  \n                                     0.05132  \ncte.achievementCTE Concentrator or Completor  \n                                     0.48217  \n              cte.achievementCTE Participant  \n                                     0.31995  \n                                       MCA.M  \n                                    -0.01354  \n                           pseo.participant1  \n                                    -0.17932  \n                              attended.psYes  \n                                     0.04668  \n\nDegrees of Freedom: 19937 Total (i.e. Null);  19922 Residual\n  (1330 observations deleted due to missingness)\nNull Deviance:\t    23420 \nResidual Deviance: 22880 \tAIC: 22910\n```\n\n\n:::\n\n```{.r .cell-code}\nor_plot <- tidy(model2, conf.int = TRUE, exponentiate = TRUE) %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(\n    # Make labels nicer (edit these replacements to match your exact factor labels)\n    term = str_replace_all(term, c(\n      \"RaceEthnicity\" = \"Race: \",\n      \"economic.status\" = \"Economic status: \",\n      \"SpecialEdStatus\" = \"Special Ed: \",\n      \"pseo.participant\" = \"PSEO: \",\n      \"cte.achievement\" = \"CTE: \",\n      \"MCA.R\" = \"MCA Reading\",\n      \"MCA.M\" = \"MCA Math\",\n      \"Dem_Desc\" = \"Dem_Desc: \",\n      \"Gender\" = \"Gender: \",\n      \"took.ACT\" = \"Took ACT: \"\n    )),\n    # Put most important effects near the top (optional: tweak ordering later)\n    term = fct_reorder(term, estimate)\n  )\n\nggplot(or_plot, aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\") +\n  geom_vline(xintercept = c(0.5, 0.75, 1.25, 1.5, 2),\n             color = \"grey85\") +\n  geom_point() +\n  geom_errorbar(\n    aes(xmin = conf.low, xmax = conf.high),\n    orientation = \"y\",\n    width = 0.2\n  ) +\n  scale_x_log10(\n    breaks = c(0.5, 0.75, 1, 1.25, 1.5, 2),\n    labels = c(\"0.5\", \"0.75\", \"1.0\", \"1.25\", \"1.5\", \"2.0\")\n  ) +\n  theme_line +\n  labs(\n    x = \"Odds ratio (log scale)\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](analysis_multivariate_confirmation_non_college_grads_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\n<br>\n\n## Model 3 — Year 5: Adding Local Labor Market Context\n\nModel 3 adds county-level unemployment rate and wages as a percent of state average to the full Model 2 specification, producing a very modest improvement in model fit (AIC = 22,900 vs. 22,910 in Model 2, residual deviance = 22,870 vs. 22,880). While minimal, this represents a slight improvement over year 1 where the labor market variables added nothing at all, suggesting local economic context begins to play a modest role in regional workforce attachment by year 5.\n\n**All core associations from Model 2 remain stable:**\n\n-   CTE concentrators and completers retain approximately 65% higher odds of regional employment (OR = 1.647, p \\< .001), slightly stronger than in Model 2 (OR = 1.620)\n-   CTE participants retain approximately 38% higher odds (OR = 1.384, p \\< .001), essentially unchanged from Model 2\n-   Attended post-secondary remains non-significant (OR = 1.045, p = .180), confirming its earlier dissipation at year 5\n-   PSEO participation retains its negative association (OR = 0.846, p = .001)\n-   Gender retains approximately 20% lower odds for females (OR = 0.798, p \\< .001), essentially unchanged from Model 2\n-   Special education status remains non-significant (OR = 0.979, p = .622)\n-   Economic status remains non-significant (OR = 0.982, p = .587)\n\n**Community type associations shift modestly with the addition of labor market variables:**\n\n-   Entirely urban non-completers show approximately 50% lower odds of regional employment (OR = 0.501, p \\< .001), a modest improvement from Model 2 (OR = 0.467), suggesting that some of the urban penalty is explained by the lower wage and higher unemployment context of urban counties in NW Minnesota\n-   Town/rural mix students retain modestly higher odds (OR = 1.169, p = .004)\n-   Urban/town/rural mix students remain non-significant (OR = 1.058, p = .358)\n\n**Average unemployment rate shows a significant and now intuitive association at year 5:**\n\n-   Higher county unemployment is associated with approximately 3% higher odds of regional employment per unit increase (OR = 1.030, p = .007) — a small but statistically significant effect in the expected direction\n-   This contrasts sharply with the counterintuitive bivariate finding and the non-significant year 1 result, suggesting that once individual and community characteristics are controlled, living in a higher unemployment county is modestly associated with staying in the regional labor market rather than leaving it — consistent with a constrained mobility interpretation\n\n**Average wages as a percent of state average** remains non-significant at year 5 (OR = 1.174, p = .410), consistent with year 1\n\n**Race/ethnicity** disparities remain substantial and largely unchanged from Model 2:\n\n-   Black non-completers retain approximately 49% lower odds (OR = 0.513, p \\< .001)\n-   Hispanic non-completers retain approximately 31% lower odds (OR = 0.695, p \\< .001)\n-   Asian/PI non-completers retain approximately 39% lower odds (OR = 0.615, p = .010)\n-   American Indian non-completers remain non-significant (OR = 0.937, p = .303)\n\n*Model note: The year 5 Model 3 reveals an important and interpretively rich finding — the unemployment rate emerges as a modest but significant associate of regional employment in the expected direction once other variables are controlled, reversing the counterintuitive bivariate pattern. This suggests that the earlier bivariate finding was indeed a compositional artifact, and that by year 5 local labor market context begins to play a small independent role in shaping regional workforce attachment. CTE engagement remains the dominant modifiable associate throughout, while racial and ethnic disparities persist net of all other variables.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- glm(\n  grad.year.5 ~\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    Gender +\n    Dem_Desc +\n    cte.achievement +\n    attended.ps +\n    MCA.M +\n    pseo.participant +\n    avg.unemp.rate +\n    avg.wages.pct.state,\n  family = binomial,\n  data = master.model.5\n)\n\nmodel3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = grad.year.5 ~ RaceEthnicity + economic.status + \n    SpecialEdStatus + Gender + Dem_Desc + cte.achievement + attended.ps + \n    MCA.M + pseo.participant + avg.unemp.rate + avg.wages.pct.state, \n    family = binomial, data = master.model.5)\n\nCoefficients:\n                                 (Intercept)  \n                                    -1.50542  \n                             RaceEthnicityAI  \n                                    -0.06508  \n                       RaceEthnicityAsian/PI  \n                                    -0.48651  \n                          RaceEthnicityBlack  \n                                    -0.66843  \n                       RaceEthnicityHispanic  \n                                    -0.36444  \n                            economic.status1  \n                                    -0.01849  \n                            SpecialEdStatus1  \n                                    -0.02080  \n                                     GenderF  \n                                    -0.22548  \n                      Dem_DescEntirely urban  \n                                    -0.69080  \n                      Dem_DescTown/rural mix  \n                                     0.15621  \n                Dem_DescUrban/town/rural mix  \n                                     0.05647  \ncte.achievementCTE Concentrator or Completor  \n                                     0.49873  \n              cte.achievementCTE Participant  \n                                     0.32472  \n                              attended.psYes  \n                                     0.04430  \n                                       MCA.M  \n                                    -0.00609  \n                           pseo.participant1  \n                                    -0.16761  \n                              avg.unemp.rate  \n                                     0.02974  \n                         avg.wages.pct.state  \n                                     0.16029  \n\nDegrees of Freedom: 19937 Total (i.e. Null);  19920 Residual\n  (1330 observations deleted due to missingness)\nNull Deviance:\t    23420 \nResidual Deviance: 22870 \tAIC: 22900\n```\n\n\n:::\n\n```{.r .cell-code}\nor_plot <- tidy(model3, conf.int = TRUE, exponentiate = TRUE) %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(\n    # Make labels nicer (edit these replacements to match your exact factor labels)\n    term = str_replace_all(term, c(\n      \"RaceEthnicity\" = \"Race: \",\n      \"economic.status\" = \"Economic status: \",\n      \"SpecialEdStatus\" = \"Special Ed: \",\n      \"pseo.participant\" = \"PSEO: \",\n      \"cte.achievement\" = \"CTE: \",\n      \"MCA.R\" = \"MCA Reading\",\n      \"MCA.M\" = \"MCA Math\",\n      \"Dem_Desc\" = \"Dem_Desc: \",\n      \"Gender\" = \"Gender: \",\n      \"took.ACT\" = \"Took ACT: \",\n      \"avg.unemp.rate\" = \"Avg unemp rate\",\n      \"avg.wages.pct.state\" = \"Avg wages pct state\"\n    )),\n    # Put most important effects near the top (optional: tweak ordering later)\n    term = fct_reorder(term, estimate)\n  )\n\nggplot(or_plot, aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\") +\n  geom_vline(xintercept = c(0.5, 0.75, 1.25, 1.5, 2),\n             color = \"grey85\") +\n  geom_point() +\n  geom_errorbar(\n    aes(xmin = conf.low, xmax = conf.high),\n    orientation = \"y\",\n    width = 0.2\n  ) +\n  scale_x_log10(\n    breaks = c(0.5, 0.75, 1, 1.25, 1.5, 2),\n    labels = c(\"0.5\", \"0.75\", \"1.0\", \"1.25\", \"1.5\", \"2.0\")\n  ) +\n  theme_line +\n  labs(\n    x = \"Odds ratio (log scale)\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](analysis_multivariate_confirmation_non_college_grads_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\n<br>\n\n# Modeling - `grad.year.10`\n\n## Model 1 — Year 10: Structural and Demographic Baseline\n\nModel 1 establishes the baseline associations between demographic characteristics and community type with meaningful regional employment ten years after high school, prior to the inclusion of any high school preparation variables. The model shows modest improvement over the null (AIC = 13,630, residual deviance = 13,610 vs. null deviance = 13,910), consistent with the pattern across all three time points that structural factors alone explain only a limited portion of regional workforce attachment.\n\n**Gender** retains a strong and stable association at year 10:\n\n-   Females have approximately 26% lower odds of meaningful regional employment relative to males (OR = 0.742, p \\< .001), consistent with year 5 (OR = 0.746) and suggesting the gender gap in regional workforce attachment stabilizes rather than continues to widen after year 5\n\n**Community type** shows its strongest associations yet, driven almost entirely by the urban penalty:\n\n-   Entirely urban non-completers have approximately 63% lower odds of meaningful regional employment relative to entirely rural students (OR = 0.371, p \\< .001), the largest urban penalty observed across all three time points and the strongest single association in the model. This growing penalty suggests that urban non-completers become increasingly disconnected from the regional labor market over time rather than eventually finding their footing\n-   Town/rural mix students are no longer significantly associated with higher regional employment at year 10 (OR = 1.059, p = .411), a notable shift from years 1 and 5 where this group showed consistently higher odds\n-   Urban/town/rural mix students also show no significant association (OR = 1.029, p = .714)\n\n**Race/ethnicity** disparities remain substantial at year 10:\n\n-   Asian/PI non-completers show the largest racial/ethnic disparity in the model (OR = 0.287, p \\< .001), substantially larger than at year 5 (OR = 0.484)\n-   Black non-completers retain approximately 53% lower odds (OR = 0.466, p \\< .001), consistent with year 5\n-   Hispanic non-completers show approximately 29% lower odds (OR = 0.714, p = .008), somewhat attenuated from year 5 (OR = 0.597)\n-   American Indian non-completers remain non-significant (OR = 0.956, p = .568)\n\n**Special education status** shows a notable reversal at year 10:\n\n-   The association is no longer significant and flips direction (OR = 1.056, p = .282), suggesting that by year 10 special education status carries no meaningful independent association with regional employment — a complete turnaround from year 1 where it showed approximately 21% lower odds\n\n**Economic status** remains non-significant across all three time points (OR = 0.970, p = .498)\n\n*Model note: The year 10 baseline model reveals two key developments — the urban penalty continues to intensify over time while the town/rural mix advantage disappears, and special education status fully dissipates and reverses direction. Racial and ethnic disparities remain substantial, particularly for Asian/PI and Black non-completers. The introduction of high school preparation variables in Model 2 will test whether these long-term structural patterns persist once career alignment is accounted for.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- glm(\n  grad.year.10 ~\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    Gender +\n    Dem_Desc,\n  family = binomial,\n  data = master.model.10\n)\n\nmodel1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = grad.year.10 ~ RaceEthnicity + economic.status + \n    SpecialEdStatus + Gender + Dem_Desc, family = binomial, data = master.model.10)\n\nCoefficients:\n                 (Intercept)               RaceEthnicityAI  \n                    -0.92902                      -0.04492  \n       RaceEthnicityAsian/PI            RaceEthnicityBlack  \n                    -1.24876                      -0.76333  \n       RaceEthnicityHispanic              economic.status1  \n                    -0.33637                      -0.03005  \n            SpecialEdStatus1                       GenderF  \n                     0.05476                      -0.29801  \n      Dem_DescEntirely urban        Dem_DescTown/rural mix  \n                    -0.99037                       0.05703  \nDem_DescUrban/town/rural mix  \n                     0.02882  \n\nDegrees of Freedom: 12596 Total (i.e. Null);  12586 Residual\nNull Deviance:\t    13910 \nResidual Deviance: 13610 \tAIC: 13630\n```\n\n\n:::\n\n```{.r .cell-code}\nor_plot <- tidy(model1, conf.int = TRUE, exponentiate = TRUE) %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(\n    # Make labels nicer (edit these replacements to match your exact factor labels)\n    term = str_replace_all(term, c(\n      \"RaceEthnicity\" = \"Race: \",\n      \"economic.status\" = \"Economic status: \",\n      \"Gender\" = \"Gender: \",\n      \"SpecialEdStatus\" = \"Special Ed: \",\n      \"Dem_Desc\" = \"Dem_Desc: \"\n    )),\n    # Put most important effects near the top (optional: tweak ordering later)\n    term = fct_reorder(term, estimate)\n  )\n\nggplot(or_plot, aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\") +\n  geom_vline(xintercept = c(0.5, 0.75, 1.25, 1.5, 2),\n             color = \"grey85\") +\n  geom_point() +\n  geom_errorbar(\n    aes(xmin = conf.low, xmax = conf.high),\n    orientation = \"y\",\n    width = 0.2\n  ) +\n  scale_x_log10(\n    breaks = c(0.5, 0.75, 1, 1.25, 1.5, 2),\n    labels = c(\"0.5\", \"0.75\", \"1.0\", \"1.25\", \"1.5\", \"2.0\")\n  ) +\n  theme_line +\n  labs(\n    x = \"Odds ratio (log scale)\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](analysis_multivariate_confirmation_non_college_grads_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\n<br>\n\n## Model 2 — Year 10: Adding High School Accomplishments\n\nModel 2 introduces high school preparation variables alongside the structural baseline, producing meaningful improvement in model fit (AIC = 12,870 vs. 13,630 in Model 1, residual deviance = 12,840 vs. 13,610). Note that 935 observations are lost due to missing MCA scores, so direct AIC comparison with Model 1 should be interpreted with some caution.\n\n**CTE achievement** retains a significant and positive association at year 10, though attenuated compared to earlier time points:\n\n-   CTE concentrators and completers have approximately 40% higher odds of meaningful regional employment relative to non-CTE students (OR = 1.401, p \\< .001), down from approximately 62% at year 5 and 70% at year 1, suggesting CTE's regional retention effect moderates over time but remains a durable and independent associate\n-   CTE participants have approximately 27% higher odds relative to non-CTE students (OR = 1.275, p \\< .001), also attenuated from year 5 (OR = 1.377)\n\n**MCA Math emerges as a significant negative associate at year 10:**\n\n-   Higher math proficiency is associated with approximately 13% lower odds of meaningful regional employment per unit increase (OR = 0.872, p \\< .001), the first time MCA Math reaches significance across the three time points and in the expected direction — confirming the bivariate finding that academic proficiency increasingly predicts out-of-region mobility as careers develop\n\n**Attended post-secondary reverses direction at year 10:**\n\n-   Non-completers who attended post-secondary now show approximately 10% lower odds of meaningful regional employment (OR = 0.902, p = .020), a complete reversal from year 1 where it showed approximately 69% higher odds. This suggests that by year 10, post-secondary exposure — even without completion — is associated with outward labor market mobility rather than regional attachment, mirroring the pattern seen for academic proficiency\n\n**PSEO participation** is no longer significant at year 10 (OR = 1.027, p = .748), reversing from its consistent negative association at years 1 and 5. By year 10, early college exposure no longer differentiates regional from non-regional employment outcomes\n\n**Community type** associations remain dominated by the urban penalty:\n\n-   Entirely urban non-completers retain approximately 63% lower odds of regional employment relative to entirely rural students (OR = 0.373, p \\< .001), essentially unchanged from the year 10 baseline model and confirming that the urban penalty is fully structural and independent of preparation variables\n-   Town/rural mix and urban/town/rural mix students remain non-significant, consistent with Model 1\n\n**Gender** retains a stable association:\n\n-   Females have approximately 24% lower odds of meaningful regional employment relative to males (OR = 0.763, p \\< .001), consistent across all three time points\n\n**Economic status** reaches marginal significance at year 10:\n\n-   Economically disadvantaged students show approximately 9% lower odds of regional employment (OR = 0.912, p = .046), the first time economic status shows any significant association across the three time points, though the magnitude remains small\n\n**Special education status** remains non-significant at year 10 (OR = 0.997, p = .962)\n\n**Race/ethnicity** disparities persist:\n\n-   Asian/PI non-completers retain approximately 61% lower odds (OR = 0.395, p = .001)\n-   Black non-completers retain approximately 48% lower odds (OR = 0.518, p = .001)\n-   Hispanic non-completers are no longer significant at year 10 (OR = 0.785, p = .073)\n-   American Indian non-completers remain non-significant (OR = 0.919, p = .304)\n\n*Model note: The year 10 Model 2 reveals the most dramatic shifts in the analysis. MCA Math becomes a significant negative associate for the first time, attended post-secondary reverses from strongly positive to modestly negative, and PSEO participation loses its earlier negative association entirely. Together these shifts confirm that academic preparation variables increasingly predict out-of-region mobility rather than regional attachment as careers mature. CTE engagement remains the only preparation variable that retains a consistently positive association with regional workforce attachment across all three time points. Model 3 will test whether local labor market context explains any remaining variation at the 10-year mark.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- glm(\n  grad.year.10 ~\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    Gender +\n    Dem_Desc +\n    cte.achievement +\n    attended.ps +\n    MCA.M +\n    pseo.participant,\n  family = binomial,\n  data = master.model.10\n)\n\nmodel2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = grad.year.10 ~ RaceEthnicity + economic.status + \n    SpecialEdStatus + Gender + Dem_Desc + cte.achievement + attended.ps + \n    MCA.M + pseo.participant, family = binomial, data = master.model.10)\n\nCoefficients:\n                                 (Intercept)  \n                                   -0.753626  \n                             RaceEthnicityAI  \n                                   -0.084891  \n                       RaceEthnicityAsian/PI  \n                                   -0.928702  \n                          RaceEthnicityBlack  \n                                   -0.658674  \n                       RaceEthnicityHispanic  \n                                   -0.241765  \n                            economic.status1  \n                                   -0.091618  \n                            SpecialEdStatus1  \n                                   -0.002681  \n                                     GenderF  \n                                   -0.270094  \n                      Dem_DescEntirely urban  \n                                   -0.985034  \n                      Dem_DescTown/rural mix  \n                                    0.073245  \n                Dem_DescUrban/town/rural mix  \n                                    0.028722  \ncte.achievementCTE Concentrator or Completor  \n                                    0.337481  \n              cte.achievementCTE Participant  \n                                    0.242920  \n                              attended.psYes  \n                                   -0.103106  \n                                       MCA.M  \n                                   -0.137324  \n                           pseo.participant1  \n                                    0.027007  \n\nDegrees of Freedom: 11661 Total (i.e. Null);  11646 Residual\n  (935 observations deleted due to missingness)\nNull Deviance:\t    13200 \nResidual Deviance: 12840 \tAIC: 12870\n```\n\n\n:::\n\n```{.r .cell-code}\nor_plot <- tidy(model2, conf.int = TRUE, exponentiate = TRUE) %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(\n    # Make labels nicer (edit these replacements to match your exact factor labels)\n    term = str_replace_all(term, c(\n      \"RaceEthnicity\" = \"Race: \",\n      \"economic.status\" = \"Economic status: \",\n      \"SpecialEdStatus\" = \"Special Ed: \",\n      \"pseo.participant\" = \"PSEO: \",\n      \"cte.achievement\" = \"CTE: \",\n      \"MCA.R\" = \"MCA Reading\",\n      \"MCA.M\" = \"MCA Math\",\n      \"Dem_Desc\" = \"Dem_Desc: \",\n      \"Gender\" = \"Gender: \",\n      \"took.ACT\" = \"Took ACT: \"\n    )),\n    # Put most important effects near the top (optional: tweak ordering later)\n    term = fct_reorder(term, estimate)\n  )\n\nggplot(or_plot, aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\") +\n  geom_vline(xintercept = c(0.5, 0.75, 1.25, 1.5, 2),\n             color = \"grey85\") +\n  geom_point() +\n  geom_errorbar(\n    aes(xmin = conf.low, xmax = conf.high),\n    orientation = \"y\",\n    width = 0.2\n  ) +\n  scale_x_log10(\n    breaks = c(0.5, 0.75, 1, 1.25, 1.5, 2),\n    labels = c(\"0.5\", \"0.75\", \"1.0\", \"1.25\", \"1.5\", \"2.0\")\n  ) +\n  theme_line +\n  labs(\n    x = \"Odds ratio (log scale)\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](analysis_multivariate_confirmation_non_college_grads_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n\n<br>\n\n## Model 3 — Year 10: Adding Local Labor Market Context\n\nModel 3 adds county-level unemployment rate and wages as a percent of state average to the full Model 2 specification, producing meaningful improvement in model fit (AIC = 12,840 vs. 12,870 in Model 2, residual deviance = 12,800 vs. 12,840) — the largest improvement produced by the labor market variables across all three time points. This confirms that local economic context becomes an increasingly important mechanism shaping regional workforce attachment as careers mature.\n\n**Both labor market variables are significant at year 10 for the first time:**\n\n-   Higher county unemployment rate is associated with approximately 11% higher odds of regional employment per unit increase (OR = 1.108, p \\< .001), a substantial and intuitive finding — individuals in higher unemployment counties are more likely to remain in the regional labor market, consistent with a constrained mobility interpretation where limited outside opportunities anchor workers locally\n-   Higher county wages as a percent of state average are associated with approximately 113% higher odds of regional employment (OR = 2.130, p = .005), suggesting that counties with stronger relative wage environments are substantially better at retaining non-college completers in meaningful regional employment over the long term\n\n**The urban penalty moderates meaningfully with the addition of labor market variables:**\n\n-   Entirely urban non-completers show approximately 51% lower odds of regional employment (OR = 0.488, p \\< .001), compared to 63% lower odds in Model 2, indicating that a meaningful portion of the urban penalty at year 10 is explained by the lower wage and different unemployment context of urban counties in NW Minnesota\n-   Town/rural mix and urban/town/rural mix students remain non-significant, consistent with Model 2\n\n**CTE achievement strengthens slightly with the addition of labor market variables:**\n\n-   CTE concentrators and completers now show approximately 51% higher odds of regional employment (OR = 1.513, p \\< .001), up from 40% in Model 2, suggesting that CTE's regional retention effect is slightly understated when local economic context is not accounted for\n-   CTE participants retain approximately 28% higher odds (OR = 1.284, p \\< .001), essentially unchanged from Model 2\n\n**MCA Math retains its significant negative association:**\n\n-   Higher math proficiency continues to associate with approximately 14% lower odds of regional employment per unit increase (OR = 0.857, p \\< .001), slightly stronger than in Model 2 (OR = 0.872), confirming academic proficiency as an out-of-region mobility signal that persists net of local economic conditions\n\n**Attended post-secondary retains its modest negative association:**\n\n-   Non-completers who attended post-secondary show approximately 9% lower odds of regional employment (OR = 0.914, p = .045), consistent with Model 2 and confirming the reversal of direction at year 10\n\n**Gender** retains a stable and significant association:\n\n-   Females have approximately 23% lower odds of regional employment (OR = 0.768, p \\< .001), essentially unchanged across all three models at year 10\n\n**Economic status** retains marginal significance:\n\n-   Economically disadvantaged students show approximately 10% lower odds of regional employment (OR = 0.902, p = .025), consistent with Model 2\n\n**Special education status** remains non-significant (OR = 0.990, p = .864)\n\n**PSEO participation** remains non-significant (OR = 1.028, p = .749)\n\n**Race/ethnicity** disparities persist net of all variables:\n\n-   Asian/PI non-completers retain approximately 60% lower odds (OR = 0.396, p = .001)\n-   Black non-completers retain approximately 49% lower odds (OR = 0.515, p = .001)\n-   Hispanic non-completers remain non-significant (OR = 0.801, p = .101)\n-   American Indian non-completers remain non-significant (OR = 0.917, p = .310)\n\n*Model note: The year 10 Model 3 is the most revealing of all nine models in the analysis. Both labor market variables reach significance for the first time, producing the largest model fit improvement across the three time points and moderating the urban penalty meaningfully. Together with the significant MCA Math and reversed attended.ps associations, this model confirms that long-term regional workforce attachment among non-college completers is shaped by a combination of early career alignment through CTE, local economic opportunity structures, and outward mobility pressures associated with academic proficiency and post-secondary exposure — all operating within persistent structural inequalities by race/ethnicity and gender.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- glm(\n  grad.year.10 ~\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    Gender +\n    Dem_Desc +\n    cte.achievement +\n    attended.ps +\n    MCA.M +\n    pseo.participant +\n    avg.unemp.rate +\n    avg.wages.pct.state,\n  family = binomial,\n  data = master.model.10\n)\n\nmodel3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = grad.year.10 ~ RaceEthnicity + economic.status + \n    SpecialEdStatus + Gender + Dem_Desc + cte.achievement + attended.ps + \n    MCA.M + pseo.participant + avg.unemp.rate + avg.wages.pct.state, \n    family = binomial, data = master.model.10)\n\nCoefficients:\n                                 (Intercept)  \n                                   -2.094096  \n                             RaceEthnicityAI  \n                                   -0.086888  \n                       RaceEthnicityAsian/PI  \n                                   -0.926960  \n                          RaceEthnicityBlack  \n                                   -0.663817  \n                       RaceEthnicityHispanic  \n                                   -0.221446  \n                            economic.status1  \n                                   -0.102925  \n                            SpecialEdStatus1  \n                                   -0.009804  \n                                     GenderF  \n                                   -0.264248  \n                      Dem_DescEntirely urban  \n                                   -0.717968  \n                      Dem_DescTown/rural mix  \n                                    0.084438  \n                Dem_DescUrban/town/rural mix  \n                                    0.043402  \ncte.achievementCTE Concentrator or Completor  \n                                    0.413912  \n              cte.achievementCTE Participant  \n                                    0.249719  \n                              attended.psYes  \n                                   -0.089470  \n                                       MCA.M  \n                                   -0.154713  \n                           pseo.participant1  \n                                    0.027233  \n                              avg.unemp.rate  \n                                    0.102303  \n                         avg.wages.pct.state  \n                                    0.755943  \n\nDegrees of Freedom: 11661 Total (i.e. Null);  11644 Residual\n  (935 observations deleted due to missingness)\nNull Deviance:\t    13200 \nResidual Deviance: 12800 \tAIC: 12840\n```\n\n\n:::\n\n```{.r .cell-code}\nor_plot <- tidy(model3, conf.int = TRUE, exponentiate = TRUE) %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(\n    # Make labels nicer (edit these replacements to match your exact factor labels)\n    term = str_replace_all(term, c(\n      \"RaceEthnicity\" = \"Race: \",\n      \"economic.status\" = \"Economic status: \",\n      \"SpecialEdStatus\" = \"Special Ed: \",\n      \"pseo.participant\" = \"PSEO: \",\n      \"cte.achievement\" = \"CTE: \",\n      \"MCA.R\" = \"MCA Reading\",\n      \"MCA.M\" = \"MCA Math\",\n      \"Dem_Desc\" = \"Dem_Desc: \",\n      \"Gender\" = \"Gender: \",\n      \"took.ACT\" = \"Took ACT: \",\n      \"avg.unemp.rate\" = \"Avg unemp rate\",\n      \"avg.wages.pct.state\" = \"Avg wages pct state\"\n    )),\n    # Put most important effects near the top (optional: tweak ordering later)\n    term = fct_reorder(term, estimate)\n  )\n\nggplot(or_plot, aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\") +\n  geom_vline(xintercept = c(0.5, 0.75, 1.25, 1.5, 2),\n             color = \"grey85\") +\n  geom_point() +\n  geom_errorbar(\n    aes(xmin = conf.low, xmax = conf.high),\n    orientation = \"y\",\n    width = 0.2\n  ) +\n  scale_x_log10(\n    breaks = c(0.5, 0.75, 1, 1.25, 1.5, 2),\n    labels = c(\"0.5\", \"0.75\", \"1.0\", \"1.25\", \"1.5\", \"2.0\")\n  ) +\n  theme_line +\n  labs(\n    x = \"Odds ratio (log scale)\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](analysis_multivariate_confirmation_non_college_grads_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n\n<br>\n\n# Multivariate Confirmation Analysis Summary — Non-College Completers in Northwest Minnesota\n\nAcross nine logistic regression models estimated at years 1, 5, and 10 after high school, the multivariate confirmation analysis clarifies the mechanisms underlying sustained regional employment among Northwest Minnesota's non-college completers. The structured sequential modeling approach — introducing demographic baseline, high school preparation, and local labor market context in successive steps — allows examination of how these mechanisms shift across the first decade after high school. Several findings from the earlier bivariate and persistence analyses are confirmed, extended, or importantly nuanced by the multivariate results.\n\n## CTE Engagement Is the Most Consistent and Durable Associate\n\nAcross all three time points and all three model specifications, CTE achievement retains a significant, positive, and independent association with meaningful regional employment. No other variable in the analysis matches this consistency.\n\n-   At year 1, CTE concentrators and completers show approximately 70% higher odds of regional employment relative to non-CTE students (OR = 1.695), surviving adjustment for demographics, community type, post-secondary attendance, academic readiness, and PSEO participation\n-   At year 5, the association moderates slightly but remains robust (OR = 1.647 in Model 3), with CTE participants also showing a strengthening association compared to year 1\n-   At year 10, CTE concentrators and completers retain approximately 51% higher odds (OR = 1.513 in Model 3), the only preparation variable to maintain a consistently positive association across all three time points\n-   Importantly, CTE's association strengthens slightly when local labor market context is added at year 10, suggesting its regional retention effect is slightly understated when economic conditions are not accounted for\n\nThe dose-response pattern identified in the bivariate analysis — with concentrators and completers showing stronger associations than participants — is confirmed and sustained across all nine models. CTE engagement is not merely a short-term workforce anchor but a durable mechanism of regional labor market attachment.\n\n## Post-Secondary Attendance and Academic Proficiency Shift Direction Over Time\n\nTwo of the most striking findings in the multivariate analysis involve variables whose direction of association reverses across time points — a pattern that could not be detected in the bivariate analysis alone.\n\n**Attended post-secondary** shows the most dramatic trajectory:\n\n-   At year 1, it is the strongest positive associate in the model (OR = 1.690), suggesting that even incomplete post-secondary exposure provides immediate regional workforce benefits\n-   By year 5, the association dissipates entirely and becomes non-significant (OR = 1.045)\n-   By year 10, it reverses to a modest but significant negative association (OR = 0.914), indicating that post-secondary attendance — even without completion — is associated with outward labor market mobility over the long term\n\n**MCA Math** follows a similar but more gradual trajectory:\n\n-   At years 1 and 5, MCA Math shows no significant association with regional employment, consistent with bivariate findings\n-   By year 10, it emerges as a significant negative associate (OR = 0.857 in Model 3), confirming that higher academic proficiency increasingly predicts out-of-region employment as careers mature\n\nTogether, these two trajectories tell a coherent story — individuals with stronger academic preparation and post-secondary exposure are initially more likely to be present in the regional labor market but increasingly likely to leave it over time as they access broader labor market opportunities.\n\n## Local Labor Market Context Becomes Increasingly Important Over Time\n\nThe role of local economic conditions evolves substantially across the three time points, shifting from irrelevant at year 1 to meaningfully explanatory by year 10.\n\n-   At year 1, neither unemployment rate nor county wages show significant independent associations, and the addition of these variables produces no improvement in model fit. The counterintuitive bivariate pattern for unemployment rate does not survive multivariate adjustment, confirming it was a compositional artifact\n-   At year 5, the unemployment rate emerges as a modest but significant positive associate (OR = 1.030), suggesting that by mid-career, local labor market constraints begin to shape regional workforce attachment\n-   At year 10, both variables reach significance — unemployment rate (OR = 1.108) and county wages (OR = 2.130) — producing the largest model fit improvement across all three time points. Higher unemployment constrains outward mobility while higher relative wages provide a stronger incentive to remain in the region\n\nThe moderating effect of labor market variables on the urban penalty at year 10 — reducing it from approximately 63% lower odds in Model 2 to 51% lower odds in Model 3 — confirms that a meaningful portion of urban non-completers' long-term disconnection reflects the economic context of urban NW Minnesota rather than purely individual characteristics.\n\n## The Urban Penalty Is Structural, Persistent, and Growing\n\nCommunity type — captured by Dem_Desc — is the strongest geographic associate throughout the analysis and shows no signs of attenuating over time.\n\n-   The entirely urban penalty grows from approximately 40% lower odds at year 1 to 53% at year 5 and 51% at year 10 (after labor market adjustment), suggesting that urban non-completers become increasingly disconnected from the regional labor market rather than eventually finding their footing\n-   Critically, the urban penalty survives adjustment for all preparation and labor market variables across all three time points, indicating it reflects structural features of the urban labor market context in NW Minnesota rather than compositional differences in who attends urban schools\n-   Town/rural mix students show a consistent advantage at years 1 and 5 that dissipates by year 10, suggesting their early regional workforce advantage moderates as the labor market matures\n\n## Gender Disparities Are Persistent and Structural\n\nGender shows a stable and significant negative association for females across all nine models, with only modest variation in magnitude across time points and specifications.\n\n-   The gender gap ranges from approximately 19% lower odds at year 1 to 26% lower odds at year 5, stabilizing at approximately 23% lower odds at year 10\n-   Importantly, the gender gap persists even after controlling for CTE engagement, post-secondary attendance, academic readiness, and local labor market context, indicating it reflects structural features of the NW regional labor market — particularly its male-dominated industry composition — rather than differences in preparation or opportunity access alone\n\n## Racial and Ethnic Disparities Persist Net of All Variables\n\nRacial and ethnic disparities in regional workforce attachment are substantial, consistent, and not explained by preparation or labor market variables across any of the three time points.\n\n-   Asian/PI and Black non-completers show the largest and most persistent disparities, with approximately 49–61% lower odds of regional employment at years 5 and 10 net of all variables\n-   Hispanic non-completers show significant lower odds at years 1 and 5 that attenuate to non-significance by year 10\n-   American Indian non-completers show no significant association at any time point in the multivariate context, despite showing some bivariate differences\n-   The persistence of these disparities across all model specifications suggests they reflect structural inequities operating beyond the mechanisms captured in this analysis\n\n## Other Structural Variables Shift Over Time\n\nSeveral structural variables show time-varying patterns that add nuance to the overall picture:\n\n-   **Special education status** shows a strong negative association at year 1 (OR = 0.791 in Model 1) that attenuates substantially by year 5 and disappears entirely by year 10, confirming that its influence is concentrated in the immediate post-high school transition period\n-   **Economic status** shows no significant association at years 1 or 5 but reaches marginal significance at year 10 (OR = 0.902), suggesting that economic disadvantage has a delayed rather than immediate effect on long-term regional workforce attachment\n-   **PSEO participation** shows a consistent negative association at years 1 and 5 — reflecting its role as a college-going and out-of-region mobility marker — that disappears entirely by year 10\n\n## Overall Conclusion\n\nThe multivariate confirmation analysis clarifies and confirms the central mechanisms shaping regional workforce attachment among non-college completers in Northwest Minnesota. Three distinct phases emerge across the first decade after high school:\n\n-   **Year 1** is dominated by high school preparation effects — particularly CTE engagement and post-secondary attendance — operating alongside structural demographic and geographic characteristics. Local labor market context plays no independent role at this stage\n-   **Year 5** marks a transition — CTE remains dominant while post-secondary attendance dissipates, local labor market context begins to emerge, and racial and ethnic disparities broaden and strengthen\n-   **Year 10** reflects long-term embeddedness — CTE retains its regional retention effect, academic proficiency and post-secondary attendance shift toward predicting outward mobility, and local economic conditions emerge as meaningful independent associates of whether non-college completers remain anchored to the regional labor market\n\nAcross all three phases, CTE engagement is the only variable that consistently and positively associates with sustained regional employment. The urban penalty is the only geographic pattern that persists and grows across all time points. And racial and ethnic disparities remain substantial and unexplained by any combination of preparation, context, or structural variables included in the analysis — pointing to deeper structural inequities that warrant direct attention in workforce development and education policy.\n",
    "supporting": [
      "analysis_multivariate_confirmation_non_college_grads_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}